import type { OndoTable } from "./table-model"

/**
 * Legacy shared-ONDO fixtures. The production K-Tour ID graph deliberately
 * does not import this registry because these venue keys are not LOCALDATA
 * canonical identifiers.
 */
export const TABLES: OndoTable[] = [
  {
    id: "table-seongsu-dinner",
    venueId: "seoul-seongsu-gukbap",
    title: { en: "First gukbap together", ko: "처음 먹는 국밥 같이" },
    startsAt: "2026-08-19T19:30:00+09:00",
    hostName: "Jieun",
    hostRole: { en: "Area regular · self-declared", ko: "지역 단골 · 직접 입력" },
    seatsTaken: 2,
    seatsTotal: 5,
    languages: ["한국어", "English"],
    estimatedPriceKRW: 15_000,
    alcohol: false,
    status: "open",
    menu: { en: "Pork soup, rice and shared sides", ko: "돼지국밥, 공깃밥, 함께 먹는 반찬" },
    format: { en: "Shared dinner", ko: "함께 먹는 저녁" },
    requiresPerson: false,
    availability: "TAV-OPEN",
    fixtureId: "FX-TBL-SEOUL-DINNER",
  },
  {
    id: "table-euljiro-night",
    venueId: "seoul-euljiro-nogari",
    title: { en: "Euljiro night bites", ko: "을지로 야식 한 상" },
    startsAt: "2026-08-19T20:30:00+09:00",
    hostName: "Minjun",
    hostRole: { en: "Frequent visitor · self-declared", ko: "자주 방문함 · 직접 입력" },
    seatsTaken: 3,
    seatsTotal: 5,
    languages: ["English", "日本語"],
    estimatedPriceKRW: 25_000,
    alcohol: true,
    status: "open",
    menu: { en: "Dried pollack, fried snacks and optional beer", ko: "노가리, 튀김과 선택 주류" },
    format: { en: "Shared plates", ko: "함께 나누는 요리" },
    requiresPerson: true,
    availability: "TAV-OPEN",
    fixtureId: "FX-TBL-ALCOHOL",
  },
  {
    id: "table-mangwon-full",
    venueId: "seoul-mangwon-kalguksu",
    title: { en: "Mangwon market lunch", ko: "망원시장 점심 한 상" },
    startsAt: "2026-08-20T12:30:00+09:00",
    hostName: "Hana",
    hostRole: { en: "Market regular · self-declared", ko: "시장 단골 · 직접 입력" },
    seatsTaken: 4,
    seatsTotal: 4,
    languages: ["한국어", "English"],
    estimatedPriceKRW: 12_000,
    alcohol: false,
    status: "full",
    menu: { en: "Kalguksu and market snacks", ko: "칼국수와 시장 간식" },
    format: { en: "Market lunch", ko: "시장 점심" },
    requiresPerson: false,
    availability: "TAV-FULL",
    fixtureId: "FX-TBL-JOIN-FAIL",
  },
  {
    id: "table-busan-closed",
    venueId: "busan-jagalchi-grill",
    title: { en: "Jagalchi grilled fish", ko: "자갈치 생선구이 한 상" },
    startsAt: "2026-08-18T18:30:00+09:00",
    hostName: "Sora",
    hostRole: { en: "Busan resident · self-declared", ko: "부산 거주 · 직접 입력" },
    seatsTaken: 3,
    seatsTotal: 4,
    languages: ["한국어", "English"],
    estimatedPriceKRW: 22_000,
    alcohol: false,
    status: "closed",
    menu: { en: "Grilled fish and seasonal sides", ko: "생선구이와 제철 반찬" },
    format: { en: "Shared dinner", ko: "함께 먹는 저녁" },
    requiresPerson: false,
    availability: "TAV-CLOSED",
    fixtureId: "FX-TBL-CANCEL",
  },
  {
    id: "table-seongsu-cancelled",
    venueId: "seoul-seongsu-gukbap",
    title: { en: "Late soup stop", ko: "늦은 국밥 한 끼" },
    startsAt: "2026-08-19T22:00:00+09:00",
    hostName: "Yuna",
    hostRole: { en: "Host · self-declared", ko: "호스트 · 직접 입력" },
    seatsTaken: 1,
    seatsTotal: 4,
    languages: ["한국어", "English"],
    estimatedPriceKRW: 14_000,
    alcohol: false,
    status: "cancelled",
    menu: { en: "Soup and rice", ko: "국밥과 공깃밥" },
    format: { en: "Late supper", ko: "늦은 저녁" },
    requiresPerson: false,
    availability: "TAV-CANCELLED",
    fixtureId: "FX-TBL-CANCEL",
  },
]
