export const EXPERIENCE_COPY_B = {
  en: {
    limitedPass: "This sample pass contains only the identity-check result. Age, stay, payments and meal benefits are not included. Renewal keeps this same scope.", additionalChecks: "Review other pass checks", additionalBody: "Separately review a new prepared pass with age, stay, spending-limit and benefit examples. Consent, identity checks and saving the new pass are required. The current pass stays unchanged until then; payment checks remain separate.",
    passTitle: "Save this check in your travel pass?", passBody: "You just approved the prepared Mobile ID check for this guide. Use that same result to create and save a sample K-Tour ID pass. No second identity check or external request.", passApprove: "Create and save sample pass",
    title: "Neighborhood guide", entry: "Traveler experience", entryHint: "A small guide to the neighborhood", sample: "Preview", place: "Roba · Seoul",
    offerTitle: "Make a little more of your stop", offerBody: "Open a pocket guide with Korean-food and neighborhood tips for your next stop.",
    boundary: "This is a digital preview, not a restaurant voucher or booking. It does not include food, money or proof of a visit.",
    check: "Check my eligibility", recheck: "Check my pass again", readyTitle: "A little local inspiration, just for you", readyBody: "Your helper suggests opening the neighborhood guide. Review exactly what you are allowing below.",
    scope: "Open this guide once", recipient: "Your preview travel wallet", expiry: "Approval expires", noMoney: "No payment or transfer", approve: "Approve and open guide", consent: "I allow this one action for this recipient before the time shown.",
    running: "Opening your guide…", runningBody: "The one-time permission is being checked. Your guide is not ready yet.", unknown: "We’re checking what happened", unknownBody: "Keep this request. Starting over could repeat an action. Nothing is marked as used until its result is checked.",
    failed: "The action did not finish", failedBody: "Your guide has not been used. Retry this same request after checking your pass.",
    pending: "One last eligibility check", pendingBody: "The one-time permission was used. We still need to confirm that the guide can be provided.",
    complete: "Your local guide is ready", completeBody: "A few ideas for your next Seoul stop. This preview is saved on this browser.",
    blocked: "We couldn’t provide the guide", blockedBody: "The permission was already used, but the final check did not allow the guide. It has not been marked as used. Please review the result; do not start another execution.",
    cancelled: "This request was stopped", cancelledBody: "No guide was used. You can review a fresh proposal for this same request.",
    cancelPending: "Stop requested", cancelPendingBody: "We need to check whether the action or the stop happened first. This is not a confirmed cancellation.",
    expired: "This approval has expired", expiredBody: "Nothing further can run under this approval. Check your pass and review a fresh proposal.",
    checkResult: "Check this request", stop: "Request a stop", retry: "Review and try again", back: "Back to Roba", later: "Return for now", refresh: "Check status", error: "We couldn’t save or read this preview. Nothing new was confirmed. Try checking the same request again.",
    details: "Preview details & outcomes", detailsBody: "Prepared identity, helper and execution responses only. No external service is connected. This browser’s shared preview traveler has one guide per campaign. Saved history is not a verified credential. Clearing browser data removes this local history.",
    helper: "Prepared helper suggestion", proof: "Identity verified · yes/no only", gateTitle: "Continue with your travel account", presentationTitle: "Share identity-check eligibility?", presentationBody: "Share only the identity-check result for this guide request. No age, stay or payment information is requested.",
    authLabel: "Permission", serviceLabel: "Guide", auditLabel: "Record", auditPending: "Guide ready · record pending", auditFailed: "Guide ready · record needs another try", auditConfirmed: "Guide ready · preview record saved", auditRetry: "Retry record only",
    scenario: "Prepared response", success: "Complete normally", executionUnknown: "Execution result delayed", executionFailure: "Execution fails", serviceBlocked: "Final eligibility declines", auditDelay: "Record stays pending", auditFailure: "Record fails", cancelRace: "Execution wins the stop race",
    guideHeading: "A taste of the neighborhood", guide1: "Start with one shared dish", guide1Body: "A small shared plate lets everyone try something new. Ask which dishes are easy to share before ordering.", guide2: "Learn one useful phrase", guide2Body: "“Deol maepge hae juseyo” means “Please make it less spicy.” Allergies still need a separate, clear check with staff.", guide3: "Leave room for a walk", guide3Body: "Follow a short neighborhood loop after your meal. Choose your own pace and check crossings before putting your phone away.",
  },
  ko: {
    limitedPass: "이 샘플 패스에는 신원 확인 여부만 있어요. 나이·체류·결제·식사 혜택은 포함되지 않으며 갱신해도 범위는 같아요.", additionalChecks: "다른 패스 확인 절차 보기", additionalBody: "나이·체류·사용 한도·혜택 예시가 담긴 새 샘플 패스를 별도로 검토해요. 동의와 신원 확인, 새 패스 보관을 마치기 전에는 기존 패스가 바뀌지 않아요. 결제 확인은 여전히 별도예요.",
    passTitle: "확인한 내용을 패스에 담을까요?", passBody: "이 가이드를 위한 모바일 신분증 샘플 확인을 마쳤어요. 같은 결과로 K-Tour ID 샘플 패스를 만들고 보관해요. 신원 확인을 반복하거나 외부에 요청하지 않아요.", passApprove: "샘플 패스 만들고 보관",
    title: "골목 가이드", entry: "여행자 체험", entryHint: "이 동네를 즐기는 작은 가이드", sample: "미리보기", place: "로바 · 서울",
    offerTitle: "한 번의 방문을 조금 더 특별하게", offerBody: "다음 나들이에 참고할 한국 음식·골목 산책 팁을 작은 가이드로 열어보세요.",
    boundary: "디지털 미리보기예요. 매장 쿠폰·예약이 아니며 음식·금전·실제 방문 증명을 제공하지 않아요.",
    check: "내 이용 자격 확인", recheck: "패스 다시 확인", readyTitle: "이 동네를 즐기는 작은 제안", readyBody: "도우미가 골목 가이드 열기를 제안했어요. 허용할 대상과 범위를 확인해 주세요.",
    scope: "이 가이드 한 번 열기", recipient: "내 미리보기 여행 지갑", expiry: "승인 만료 시각", noMoney: "결제·금전 이동 없음", approve: "확인하고 가이드 열기", consent: "표시된 수령자와 기한에 한해 이 동작 한 번을 허용해요.",
    running: "가이드를 준비하고 있어요", runningBody: "한 번의 실행 권한을 확인 중이에요. 아직 가이드 제공이 끝난 것은 아니에요.", unknown: "실행 결과를 확인 중이에요", unknownBody: "같은 요청을 확인해 주세요. 처음부터 다시 실행하지 않아요. 결과 확인 전에는 사용 완료로 처리하지 않아요.",
    failed: "실행을 마치지 못했어요", failedBody: "가이드는 사용되지 않았어요. 패스를 확인한 뒤 같은 요청을 다시 시도할 수 있어요.",
    pending: "마지막 자격 확인 중이에요", pendingBody: "한 번의 실행 권한은 사용됐어요. 지금도 가이드를 제공할 수 있는지 별도로 확인해요.",
    complete: "골목 가이드가 준비됐어요", completeBody: "다음 서울 나들이를 위한 작은 아이디어예요. 이 브라우저에 미리보기를 보관했어요.",
    blocked: "가이드를 제공하지 못했어요", blockedBody: "실행 권한은 이미 사용됐지만 최종 자격 확인을 통과하지 못했어요. 가이드 사용은 0건이에요. 다시 실행하지 말고 결과를 확인해 주세요.",
    cancelled: "요청을 중단했어요", cancelledBody: "가이드는 사용되지 않았어요. 같은 요청에서 새 제안을 확인할 수 있어요.",
    cancelPending: "중단을 요청했어요", cancelPendingBody: "실행과 중단 중 무엇이 먼저 완료됐는지 확인해야 해요. 아직 취소가 확정된 것은 아니에요.",
    expired: "승인 기한이 지났어요", expiredBody: "이 승인으로는 더 진행하지 않아요. 패스를 확인하고 새 제안을 검토해 주세요.",
    checkResult: "같은 요청 확인", stop: "중단 요청", retry: "다시 확인하고 시도", back: "로바로 돌아가기", later: "일단 돌아가기", refresh: "진행 상태 확인", error: "이 미리보기를 읽거나 저장하지 못했어요. 새로 확정된 결과는 없어요. 같은 요청을 다시 확인해 주세요.",
    details: "미리보기 설명·결과 선택", detailsBody: "준비된 신원·도우미·실행 응답만 사용하며 외부 서비스는 연결되지 않았어요. 이 브라우저의 공용 체험 사용자에게 캠페인당 가이드 한 번만 제공해요. 저장된 내역은 검증된 신분증이 아니에요. 브라우저 데이터를 지우면 내역도 사라져요.",
    helper: "준비된 도우미 제안", proof: "신원 확인 여부 · 예/아니오만", gateTitle: "여행 계정으로 계속할까요?", presentationTitle: "신원 확인 여부를 공유할까요?", presentationBody: "이번 가이드 요청에 신원 확인 결과만 사용해요. 나이·체류·결제 정보는 요청하지 않아요.",
    authLabel: "실행 권한", serviceLabel: "가이드 제공", auditLabel: "결과 기록", auditPending: "가이드 준비 완료 · 기록 대기", auditFailed: "가이드 준비 완료 · 기록 재시도 필요", auditConfirmed: "가이드 준비 완료 · 미리보기 기록 저장", auditRetry: "기록만 다시 시도",
    scenario: "준비된 응답", success: "정상 완료", executionUnknown: "실행 결과 지연", executionFailure: "실행 실패", serviceBlocked: "최종 자격 확인 거절", auditDelay: "기록 대기 유지", auditFailure: "기록 실패", cancelRace: "중단보다 실행이 먼저 완료",
    guideHeading: "골목을 즐기는 세 가지 방법", guide1: "함께 먹는 한 접시부터", guide1Body: "조금씩 나눠 먹는 요리는 새로운 음식을 맛보기 좋아요. 주문 전 함께 나누기 좋은 메뉴인지 물어보세요.", guide2: "한 문장만 기억해요", guide2Body: "“덜 맵게 해주세요.” 매운맛이 걱정될 때 유용해요. 알레르기는 별도로 직원에게 정확하게 확인해 주세요.", guide3: "산책할 여유를 남겨요", guide3Body: "식사 뒤 가까운 골목을 짧게 걸어보세요. 내 속도로 즐기고, 휴대전화를 보기 전 횡단 구간부터 확인해 주세요.",
  },
  ja: {
    limitedPass: "このサンプルパスは本人確認の結果のみです。年齢・滞在・決済・食事特典は含まず、更新しても範囲は同じです。", additionalChecks: "別のパス確認手順を見る", additionalBody: "年齢・滞在・利用上限・特典の例を含む新しいサンプルパスを別途確認します。同意・本人確認・新しいパスの保存を終えるまで現在のパスは変わりません。決済の確認は別途必要です。",
    passTitle: "確認結果を旅行パスに保存しますか？", passBody: "このガイドのためのモバイル身分証サンプル確認が完了しました。同じ結果でK-Tour IDサンプルパスを作成・保存します。本人確認の繰り返しや外部への依頼はありません。", passApprove: "サンプルパスを作成・保存",
    title: "路地ガイド", entry: "旅の体験", entryHint: "この街を楽しむ小さなガイド", sample: "プレビュー", place: "ロバ · ソウル",
    offerTitle: "立ち寄りを、もう少し特別に", offerBody: "次の散策に役立つ韓国料理と街歩きのヒントを、小さなガイドで開いてみましょう。",
    boundary: "デジタルプレビューです。店舗のクーポン・予約ではなく、食事・金銭・訪問証明は提供しません。",
    check: "利用資格を確認", recheck: "パスをもう一度確認", readyTitle: "この街を楽しむ小さな提案", readyBody: "ヘルパーが路地ガイドを開くことを提案しました。許可する対象と範囲を確認してください。",
    scope: "このガイドを一回開く", recipient: "自分のプレビュー旅行ウォレット", expiry: "承認の有効期限", noMoney: "支払い・送金なし", approve: "確認してガイドを開く", consent: "表示された受取先と期限に限り、この操作を一回許可します。",
    running: "ガイドを準備しています", runningBody: "一回の実行権限を確認中です。ガイドの提供はまだ完了していません。", unknown: "実行結果を確認しています", unknownBody: "同じ依頼を確認してください。最初から実行し直さず、結果を確認するまで使用済みにはしません。",
    failed: "実行を完了できませんでした", failedBody: "ガイドは未使用です。パスを確認し、同じ依頼で再試行できます。",
    pending: "最後の資格確認中です", pendingBody: "一回の実行権限は使用されました。ガイドを提供できるか、別に確認しています。",
    complete: "路地ガイドができました", completeBody: "次のソウル散策に役立つ小さなアイデア。このブラウザにプレビューを保存しました。",
    blocked: "ガイドを提供できませんでした", blockedBody: "実行権限は使用されましたが、最終資格確認を通過しませんでした。ガイドの使用は0件です。実行し直さず結果を確認してください。",
    cancelled: "依頼を停止しました", cancelledBody: "ガイドは未使用です。同じ依頼で新しい提案を確認できます。",
    cancelPending: "停止を依頼しました", cancelPendingBody: "実行と停止のどちらが先に完了したか確認が必要です。キャンセルはまだ確定していません。",
    expired: "承認の期限が切れました", expiredBody: "この承認では進めません。パスを確認し、新しい提案を確認してください。",
    checkResult: "同じ依頼を確認", stop: "停止を依頼", retry: "確認して再試行", back: "ロバに戻る", later: "いったん戻る", refresh: "状況を確認", error: "プレビューを読み込むか保存できませんでした。新しい結果は確定していません。同じ依頼を再確認してください。",
    details: "プレビューの説明・結果", detailsBody: "用意された本人確認・ヘルパー・実行応答のみで、外部サービスには接続していません。このブラウザの共通体験利用者に、キャンペーンごとに一回提供します。保存履歴は検証済み身分証ではありません。ブラウザのデータを消すと履歴も消えます。",
    helper: "用意されたヘルパーの提案", proof: "本人確認済みか · 可否のみ", gateTitle: "旅行アカウントで続けますか？", presentationTitle: "本人確認の結果を共有？", presentationBody: "今回のガイド依頼に本人確認の結果だけを使用します。年齢・滞在・決済情報は求めません。",
    authLabel: "実行権限", serviceLabel: "ガイド提供", auditLabel: "結果記録", auditPending: "ガイド準備完了 · 記録待ち", auditFailed: "ガイド準備完了 · 記録の再試行が必要", auditConfirmed: "ガイド準備完了 · プレビュー記録保存", auditRetry: "記録のみ再試行",
    scenario: "用意された応答", success: "正常に完了", executionUnknown: "実行結果が遅延", executionFailure: "実行失敗", serviceBlocked: "最終資格確認で拒否", auditDelay: "記録待ちを維持", auditFailure: "記録失敗", cancelRace: "停止より先に実行完了",
    guideHeading: "路地を楽しむ三つのヒント", guide1: "シェアできる一皿から", guide1Body: "少しずつ分け合う料理なら、新しい味を試しやすくなります。注文前にシェアしやすい料理か聞いてみましょう。", guide2: "一つのフレーズを覚える", guide2Body: "「トル メプケ ヘ ジュセヨ」は「辛さ控えめでお願いします」。アレルギーは別にスタッフへ正確に確認してください。", guide3: "散歩の余裕を残す", guide3Body: "食後は近くの路地を少し歩いてみましょう。自分のペースで楽しみ、スマホを見る前に横断場所を確認してください。",
  },
} as const
