export const EXPERIENCE_COPY_B = {
  en: {
    limitedPass: "This sample pass contains only the identity-check result. Age, stay, payments and meal benefits are not included. Renewal keeps this same scope.", additionalChecks: "Review other pass checks", additionalBody: "Separately review a new prepared pass with age, stay, spending-limit and benefit examples. Consent, identity checks and saving the new pass are required. The current pass stays unchanged until then; payment checks remain separate.",
    passTitle: "Save this check in your travel pass?", passBody: "Use the identity check you just approved to create a sample K-Tour ID pass. No repeat check or external request. Adding the guide requires a separate approval.", passApprove: "Create and save sample pass",
    publicTitle: "Neighborhood guide", publicBody: "Three small ideas for your next Seoul stop.", addToPass: "Add to my pass", readingFree: "Read freely without signing in. Saving is optional.", returnToGuide: "Back to guide", savedGuides: "Saved guides", savedGuideHint: "A demo record in this browser’s pass collection.", viewSaveStatus: "View saved status",
    title: "Add guide to pass", entry: "Neighborhood guide", entryHint: "Read freely. Save if you like.", sample: "Preview", place: "Roba · Seoul",
    offerTitle: "Keep this guide in your pass?", offerBody: "Saving needs an identity check, a pass, consent to share the check result and your approval. Reading does not.",
    boundary: "This is a digital preview, not a restaurant voucher or booking. It does not include food, money or proof of a visit.",
    check: "Continue to save", recheck: "Check my pass again", readyTitle: "Add this guide to your pass", readyBody: "Review where this guide will be saved and how long this approval lasts.",
    scope: "Add this guide once", recipient: "Your preview pass collection", expiry: "Approval expires", noMoney: "No payment or transfer", approve: "Approve and add to pass", consent: "I allow this guide to be added once to the pass shown, before the time shown.",
    running: "Adding your guide…", runningBody: "The one-time saving action is in progress. It is not saved yet. You can keep reading.", unknown: "Checking the saving result", unknownBody: "Saving is not confirmed yet. Check this same request instead of starting again. The guide stays available to read.",
    failed: "The saving action did not finish", failedBody: "Nothing was added to your pass. You can keep reading or check your pass to retry this request.",
    pending: "Confirming the save", pendingBody: "The one-time action finished. Saving still needs a final eligibility check. Reading stays available.",
    complete: "Added to your pass", completeBody: "A demo saving record is in this browser’s pass collection. It is not an official credential.",
    blocked: "We couldn’t add this guide", blockedBody: "The one-time action finished, but the final check blocked saving. Keep reading, or check this request. Do not run the action again.",
    cancelled: "Saving was stopped", cancelledBody: "Nothing was added. Keep reading or review a new saving approval for this same request.",
    cancelPending: "Stop requested", cancelPendingBody: "We are checking whether the saving action or the stop happened first. Cancellation is not confirmed. You can keep reading.",
    expired: "Saving approval expired", expiredBody: "The guide stays available. Check your pass and review a new approval before trying to save.",
    checkResult: "Check this request", stop: "Request a stop", retry: "Review and try again", back: "Back to Roba", later: "Back to guide", refresh: "Check saving status", error: "We couldn’t read or update your saving record. You can keep reading the guide. Check this request before retrying.",
    details: "Preview details & outcomes", detailsBody: "Prepared identity, helper and execution responses only. No external service is connected. Saving is limited to once per campaign for this browser’s shared preview traveler; reading is unrestricted. This local history is not a signed VC or verified credential. Clearing browser data removes it.",
    helper: "Prepared saving proposal", proof: "Identity verified · yes/no only", gateTitle: "Continue with your travel account", presentationTitle: "Share your identity-check result?", presentationBody: "Share only the identity-check result to save this guide. No age, stay or payment information is requested. Reading needs no check.",
    authLabel: "Saving permission", serviceLabel: "Pass saving", auditLabel: "Record", auditPending: "Added to pass · record pending", auditFailed: "Added to pass · record needs another try", auditConfirmed: "Added to pass · preview record saved", auditRetry: "Retry record only",
    scenario: "Prepared response", success: "Complete normally", executionUnknown: "Execution result delayed", executionFailure: "Execution fails", serviceBlocked: "Final eligibility declines", auditDelay: "Record stays pending", auditFailure: "Record fails", cancelRace: "Execution wins the stop race",
    guideHeading: "A taste of the neighborhood", guide1: "Start with one shared dish", guide1Body: "A small shared plate lets everyone try something new. Ask which dishes are easy to share before ordering.", guide2: "Learn one useful phrase", guide2Body: "“Deol maepge hae juseyo” means “Please make it less spicy.” Allergies still need a separate, clear check with staff.", guide3: "Leave room for a walk", guide3Body: "Follow a short neighborhood loop after your meal. Choose your own pace and check crossings before putting your phone away.",
  },
  ko: {
    limitedPass: "이 샘플 패스에는 신원 확인 여부만 있어요. 나이·체류·결제·식사 혜택은 포함되지 않으며 갱신해도 범위는 같아요.", additionalChecks: "다른 패스 확인 절차 보기", additionalBody: "나이·체류·사용 한도·혜택 예시가 담긴 새 샘플 패스를 별도로 검토해요. 동의와 신원 확인, 새 패스 보관을 마치기 전에는 기존 패스가 바뀌지 않아요. 결제 확인은 여전히 별도예요.",
    passTitle: "확인한 내용을 패스에 담을까요?", passBody: "방금 동의한 신원 확인 결과로 K-Tour ID 샘플 패스를 만들어요. 확인을 반복하거나 외부에 요청하지 않아요. 가이드 담기는 별도로 승인해요.", passApprove: "샘플 패스 만들고 보관",
    publicTitle: "골목 가이드", publicBody: "다음 서울 나들이를 위한 세 가지 작은 팁이에요.", addToPass: "내 패스에 담기", readingFree: "로그인 없이 자유롭게 읽어요. 패스에 담기는 선택이에요.", returnToGuide: "가이드로 돌아가기", savedGuides: "담은 가이드", savedGuideHint: "이 브라우저의 패스 보관함에 남긴 모의 내역이에요.", viewSaveStatus: "저장 내역 보기",
    title: "가이드 담기", entry: "골목 가이드", entryHint: "자유롭게 읽고, 원하면 패스에 담아요", sample: "미리보기", place: "로바 · 서울",
    offerTitle: "이 가이드를 패스에 담을까요?", offerBody: "담을 때만 신원 확인과 패스 준비, 확인 결과 공유 동의, 저장 승인이 필요해요. 읽기는 자유로워요.",
    boundary: "디지털 미리보기예요. 매장 쿠폰·예약이 아니며 음식·금전·실제 방문 증명을 제공하지 않아요.",
    check: "담기 위해 계속하기", recheck: "패스 다시 확인", readyTitle: "패스에 담을 내용을 확인해요", readyBody: "이 가이드를 담을 곳과 승인 기한을 확인해 주세요.",
    scope: "이 가이드를 한 번 담기", recipient: "내 미리보기 패스 보관함", expiry: "승인 만료 시각", noMoney: "결제·금전 이동 없음", approve: "확인하고 패스에 담기", consent: "표시된 패스와 기한에 한해 이 가이드를 한 번 담는 데 동의해요.",
    running: "패스에 담고 있어요", runningBody: "한 번의 저장 작업을 진행 중이에요. 아직 담기는 완료되지 않았어요. 가이드는 계속 읽을 수 있어요.", unknown: "담기 결과를 확인 중이에요", unknownBody: "아직 저장을 확정하지 못했어요. 처음부터 다시 실행하지 말고 같은 요청을 확인해 주세요. 가이드는 계속 읽을 수 있어요.",
    failed: "담기를 마치지 못했어요", failedBody: "패스에 담기지 않았어요. 가이드를 읽거나, 패스를 확인한 뒤 같은 요청을 다시 시도할 수 있어요.",
    pending: "저장을 최종 확인하고 있어요", pendingBody: "한 번의 작업은 끝났어요. 패스에 담기 전에 마지막 자격 확인이 필요해요. 읽기는 계속할 수 있어요.",
    complete: "패스에 담았어요", completeBody: "이 브라우저의 패스 보관함에 모의 저장 내역을 남겼어요. 공식 증명은 아니에요.",
    blocked: "패스에 담지 못했어요", blockedBody: "한 번의 작업은 끝났지만 최종 확인에서 저장이 차단됐어요. 가이드는 읽을 수 있어요. 다시 실행하지 말고 같은 요청을 확인해 주세요.",
    cancelled: "담기를 중단했어요", cancelledBody: "패스에 담기지 않았어요. 계속 읽거나 같은 요청의 새 저장 승인을 검토할 수 있어요.",
    cancelPending: "중단을 요청했어요", cancelPendingBody: "저장 작업과 중단 중 무엇이 먼저 끝났는지 확인 중이에요. 아직 취소가 확정되지는 않았어요. 가이드는 읽을 수 있어요.",
    expired: "저장 승인 기한이 지났어요", expiredBody: "가이드는 계속 읽을 수 있어요. 담으려면 패스를 확인하고 새 승인을 검토해 주세요.",
    checkResult: "같은 요청 확인", stop: "중단 요청", retry: "다시 확인하고 시도", back: "로바로 돌아가기", later: "가이드로 돌아가기", refresh: "담기 상태 확인", error: "저장 내역을 읽거나 변경하지 못했어요. 가이드는 계속 읽을 수 있어요. 다시 시도하기 전에 같은 요청을 확인해 주세요.",
    details: "미리보기 설명·결과 선택", detailsBody: "준비된 신원·도우미·실행 응답만 사용하며 외부 서비스는 연결되지 않았어요. 이 브라우저의 공용 체험 사용자는 캠페인당 한 번 저장할 수 있으며, 읽기에는 제한이 없어요. 모의 저장 내역은 서명된 자격증명(VC)이나 검증된 신분증이 아니에요. 브라우저 데이터를 지우면 내역도 사라져요.",
    helper: "준비된 저장 제안", proof: "신원 확인 여부 · 예/아니오만", gateTitle: "여행 계정으로 계속할까요?", presentationTitle: "신원 확인 여부를 공유할까요?", presentationBody: "이 가이드를 담는 데 신원 확인 결과만 사용해요. 나이·체류·결제 정보는 요청하지 않아요. 읽기에는 확인이 필요 없어요.",
    authLabel: "저장 실행 권한", serviceLabel: "패스에 담기", auditLabel: "결과 기록", auditPending: "담기 완료 · 기록 대기", auditFailed: "담기 완료 · 기록 재시도 필요", auditConfirmed: "담기 완료 · 모의 기록 저장", auditRetry: "기록만 다시 시도",
    scenario: "준비된 응답", success: "정상 완료", executionUnknown: "실행 결과 지연", executionFailure: "실행 실패", serviceBlocked: "최종 자격 확인 거절", auditDelay: "기록 대기 유지", auditFailure: "기록 실패", cancelRace: "중단보다 실행이 먼저 완료",
    guideHeading: "골목을 즐기는 세 가지 방법", guide1: "함께 먹는 한 접시부터", guide1Body: "조금씩 나눠 먹는 요리는 새로운 음식을 맛보기 좋아요. 주문 전 함께 나누기 좋은 메뉴인지 물어보세요.", guide2: "한 문장만 기억해요", guide2Body: "“덜 맵게 해주세요.” 매운맛이 걱정될 때 유용해요. 알레르기는 별도로 직원에게 정확하게 확인해 주세요.", guide3: "산책할 여유를 남겨요", guide3Body: "식사 뒤 가까운 골목을 짧게 걸어보세요. 내 속도로 즐기고, 휴대전화를 보기 전 횡단 구간부터 확인해 주세요.",
  },
  ja: {
    limitedPass: "このサンプルパスは本人確認の結果のみです。年齢・滞在・決済・食事特典は含まず、更新しても範囲は同じです。", additionalChecks: "別のパス確認手順を見る", additionalBody: "年齢・滞在・利用上限・特典の例を含む新しいサンプルパスを別途確認します。同意・本人確認・新しいパスの保存を終えるまで現在のパスは変わりません。決済の確認は別途必要です。",
    passTitle: "確認結果を旅行パスに保存しますか？", passBody: "先ほど同意した本人確認の結果で、K-Tour IDサンプルパスを作成します。確認の繰り返しや外部への依頼はありません。ガイドの保存は別に承認します。", passApprove: "サンプルパスを作成・保存",
    publicTitle: "路地ガイド", publicBody: "次のソウル散策に役立つ、小さなヒントを三つ。", addToPass: "マイパスに保存", readingFree: "ログインなしで自由に読めます。保存は任意です。", returnToGuide: "ガイドに戻る", savedGuides: "保存したガイド", savedGuideHint: "このブラウザのパス保存一覧にある模擬履歴です。", viewSaveStatus: "保存状況を見る",
    title: "ガイドをパスに保存", entry: "路地ガイド", entryHint: "自由に読んで、気に入ったら保存", sample: "プレビュー", place: "ロバ · ソウル",
    offerTitle: "このガイドをパスに保存しますか？", offerBody: "保存には本人確認、パスの準備、確認結果の共有への同意と保存の承認が必要です。読むだけなら不要です。",
    boundary: "デジタルプレビューです。店舗のクーポン・予約ではなく、食事・金銭・訪問証明は提供しません。",
    check: "保存の手順へ", recheck: "パスをもう一度確認", readyTitle: "パスに保存する内容を確認", readyBody: "このガイドの保存先と、承認の有効期限を確認してください。",
    scope: "このガイドを一回保存", recipient: "自分のプレビューパスの保存一覧", expiry: "承認の有効期限", noMoney: "支払い・送金なし", approve: "確認してパスに保存", consent: "表示されたパスと期限に限り、このガイドを一回保存することに同意します。",
    running: "パスに保存しています", runningBody: "一回の保存操作を進めています。保存はまだ完了していません。ガイドは引き続き読めます。", unknown: "保存結果を確認しています", unknownBody: "保存はまだ確定していません。最初から実行し直さず、同じ依頼を確認してください。ガイドは引き続き読めます。",
    failed: "保存操作を完了できませんでした", failedBody: "パスには保存されていません。引き続き読むか、パスを確認して同じ依頼を再試行できます。",
    pending: "保存を最終確認しています", pendingBody: "一回の操作は完了しました。保存には最後の資格確認が必要です。読むことはできます。",
    complete: "パスに保存しました", completeBody: "このブラウザのパス保存一覧に、模擬の保存履歴を残しました。公的な証明ではありません。",
    blocked: "パスに保存できませんでした", blockedBody: "一回の操作は完了しましたが、最終確認で保存が拒否されました。ガイドは読めます。再実行せず、同じ依頼を確認してください。",
    cancelled: "保存を停止しました", cancelledBody: "パスには保存されていません。引き続き読むか、同じ依頼の新しい保存承認を確認できます。",
    cancelPending: "停止を依頼しました", cancelPendingBody: "保存操作と停止のどちらが先に完了したか確認中です。キャンセルはまだ確定していません。ガイドは読めます。",
    expired: "保存の承認期限が切れました", expiredBody: "ガイドは引き続き読めます。保存するにはパスを確認し、新しい承認を確認してください。",
    checkResult: "同じ依頼を確認", stop: "停止を依頼", retry: "確認して再試行", back: "ロバに戻る", later: "ガイドに戻る", refresh: "保存状況を確認", error: "保存履歴の読み込みか更新ができませんでした。ガイドは引き続き読めます。再試行の前に同じ依頼を確認してください。",
    details: "プレビューの説明・結果", detailsBody: "用意された本人確認・ヘルパー・実行応答のみで、外部サービスには接続していません。保存はこのブラウザの共通体験利用者につきキャンペーンごとに一回で、読む回数に制限はありません。この模擬履歴は署名済みVCや検証済み身分証ではありません。ブラウザのデータを消すと履歴も消えます。",
    helper: "用意された保存の提案", proof: "本人確認済みか · 可否のみ", gateTitle: "旅行アカウントで続けますか？", presentationTitle: "本人確認の結果を共有しますか？", presentationBody: "このガイドを保存するため、本人確認の結果だけを共有します。年齢・滞在・決済情報は求めません。読むだけなら確認は不要です。",
    authLabel: "保存の実行権限", serviceLabel: "パスへの保存", auditLabel: "結果記録", auditPending: "保存完了 · 記録待ち", auditFailed: "保存完了 · 記録の再試行が必要", auditConfirmed: "保存完了 · 模擬記録を保存", auditRetry: "記録のみ再試行",
    scenario: "用意された応答", success: "正常に完了", executionUnknown: "実行結果が遅延", executionFailure: "実行失敗", serviceBlocked: "最終資格確認で拒否", auditDelay: "記録待ちを維持", auditFailure: "記録失敗", cancelRace: "停止より先に実行完了",
    guideHeading: "路地を楽しむ三つのヒント", guide1: "シェアできる一皿から", guide1Body: "少しずつ分け合う料理なら、新しい味を試しやすくなります。注文前にシェアしやすい料理か聞いてみましょう。", guide2: "一つのフレーズを覚える", guide2Body: "「トル メプケ ヘ ジュセヨ」は「辛さ控えめでお願いします」。アレルギーは別にスタッフへ正確に確認してください。", guide3: "散歩の余裕を残す", guide3Body: "食後は近くの路地を少し歩いてみましょう。自分のペースで楽しみ、スマホを見る前に横断場所を確認してください。",
  },
} as const
