export const RESERVATION_COPY_B = {
  en: {
    title: "Book a table", sample: "Sample booking", boundary: "Prepared availability · nothing is sent to a restaurant.",
    venue: "ONDO sample restaurant", seoul: "Seoul", busan: "Busan", jeju: "Jeju", city: "City", date: "Day", time: "Time · KST", party: "People",
    request: "Request sample booking", requesting: "Requesting…", confirmed: "Your table is ready", confirmedNote: "Sample confirmation only. No real seats are reserved.",
    full: "Try another time", fullNote: "This sample time has no seats. Your choices are kept.", failed: "Request not completed", failedNote: "No sample booking was created. You can retry safely.",
    unknown: "Still checking your booking", unknownNote: "Keep this request. Check its status before trying again.",
    cancelled: "Booking cancelled", cancelledNote: "Your sample seats have been released. No charge was made.",
    cancelling: "Cancelling…", cancel_failed: "Booking is still active", cancel_failedNote: "Cancellation failed. Retry with the same booking.",
    cancel_unknown: "Cancellation is being checked", cancel_unknownNote: "Don’t make a new request yet. Check this booking’s status.",
    cancel: "Cancel booking", confirmCancel: "Cancel this sample booking?", keep: "Keep booking", query: "Check status", retry: "Retry request", retryCancel: "Retry cancellation", newBooking: "Make another booking", done: "Done",
    alternate: "Try another response", success: "Confirmed", responseFull: "No seats", failure: "Request failed", responseUnknown: "Response delayed",
    cancelResponse: "Cancellation response", cancelSuccess: "Cancelled", cancelFailure: "Failed", noAccount: "No ID check or payment is required for this sample restaurant.",
    conditions: "Booking conditions", free: "Free sample request · no deposit, wallet or account required.", cancellationPolicy: "Cancel this sample booking here without a fee. No external booking is created or cancelled.",
    returnPlace: "Return to this place", history: "Your sample bookings", switchStorage: "This place could not be opened safely. Your previous request is unchanged. Retry to open the selected place.",
    storage: "This tab couldn’t keep the sample request. Nothing new was submitted.", restore: "Your last sample request is here.", resultStorage: "The result could not be saved. Keep this request and retry saving it.", retryStorage: "Save result again",
  },
  ko: {
    title: "매장 예약", sample: "예약 샘플", boundary: "준비된 좌석 예시 · 매장으로 전송되지 않아요.",
    venue: "ONDO 샘플 레스토랑", seoul: "서울", busan: "부산", jeju: "제주", city: "도시", date: "날짜", time: "시간 · 한국 기준", party: "인원",
    request: "샘플 예약 요청", requesting: "요청 중…", confirmed: "테이블이 준비됐어요", confirmedNote: "샘플 확인서예요. 실제 좌석을 예약한 것은 아니에요.",
    full: "다른 시간을 골라볼까요?", fullNote: "이 샘플 시간은 만석이에요. 선택한 내용은 유지했어요.", failed: "요청을 완료하지 못했어요", failedNote: "생성된 샘플 예약은 없어요. 다시 요청해 보세요.",
    unknown: "예약을 확인하고 있어요", unknownNote: "새 요청 대신 현재 예약의 상태를 확인해 주세요.",
    cancelled: "예약을 취소했어요", cancelledNote: "샘플 좌석을 반환했어요. 청구된 금액은 없어요.",
    cancelling: "취소 중…", cancel_failed: "예약은 유지되고 있어요", cancel_failedNote: "취소하지 못했어요. 같은 예약으로 다시 시도해 주세요.",
    cancel_unknown: "취소 결과를 확인 중이에요", cancel_unknownNote: "새로 요청하지 말고 이 예약의 상태를 확인해 주세요.",
    cancel: "예약 취소", confirmCancel: "샘플 예약을 취소할까요?", keep: "예약 유지", query: "상태 확인", retry: "다시 요청", retryCancel: "취소 재시도", newBooking: "다른 예약 만들기", done: "완료",
    alternate: "다른 상황 체험", success: "예약 확정", responseFull: "만석", failure: "요청 실패", responseUnknown: "응답 지연",
    cancelResponse: "취소 응답", cancelSuccess: "취소 완료", cancelFailure: "취소 실패", noAccount: "이 샘플 매장은 신원확인이나 결제를 요구하지 않아요.",
    conditions: "예약 조건", free: "무료 샘플 요청 · 예약금·지갑·계정이 필요하지 않아요.", cancellationPolicy: "여기에서 수수료 없이 샘플 예약을 취소할 수 있어요. 실제 매장 예약을 생성하거나 취소하지 않아요.",
    returnPlace: "이 장소로 돌아가기", history: "내 샘플 예약", switchStorage: "선택한 장소를 안전하게 열지 못했어요. 이전 요청은 그대로예요. 다시 시도해 주세요.",
    storage: "이 탭에 샘플 요청을 보관하지 못했어요. 새 요청은 전송하지 않았어요.", restore: "마지막 샘플 요청을 이어서 볼 수 있어요.", resultStorage: "결과를 저장하지 못했어요. 같은 요청의 결과를 다시 저장해 주세요.", retryStorage: "결과 다시 저장",
  },
  ja: {
    title: "席を予約", sample: "予約サンプル", boundary: "用意された空席例・店舗には送信されません。",
    venue: "ONDOサンプルレストラン", seoul: "ソウル", busan: "釜山", jeju: "済州", city: "都市", date: "日付", time: "時間・韓国時間", party: "人数",
    request: "サンプル予約を依頼", requesting: "依頼中…", confirmed: "席の準備ができました", confirmedNote: "サンプルの確認書です。実際の席は予約されていません。",
    full: "別の時間を選びましょう", fullNote: "このサンプル時間は満席です。選択内容は保持されています。", failed: "依頼を完了できませんでした", failedNote: "サンプル予約は作成されていません。再試行できます。",
    unknown: "予約を確認しています", unknownNote: "新しく依頼せず、この予約の状況を確認してください。",
    cancelled: "予約を取り消しました", cancelledNote: "サンプルの席を解放しました。請求はありません。",
    cancelling: "取り消し中…", cancel_failed: "予約は継続しています", cancel_failedNote: "取り消しに失敗しました。同じ予約で再試行してください。",
    cancel_unknown: "取り消しを確認中", cancel_unknownNote: "新しい依頼の前に、この予約の状況を確認してください。",
    cancel: "予約を取り消す", confirmCancel: "サンプル予約を取り消しますか？", keep: "予約を維持", query: "状況を確認", retry: "再試行", retryCancel: "取り消しを再試行", newBooking: "別の予約を作成", done: "完了",
    alternate: "別のケースを試す", success: "予約確定", responseFull: "満席", failure: "依頼失敗", responseUnknown: "応答遅延",
    cancelResponse: "取り消し応答", cancelSuccess: "完了", cancelFailure: "失敗", noAccount: "このサンプル店舗では本人確認や決済は不要です。",
    conditions: "予約条件", free: "無料のサンプル依頼・予約金、ウォレット、アカウントは不要です。", cancellationPolicy: "ここで手数料なしでサンプル予約を取り消せます。実際の店舗予約の作成や取り消しは行いません。",
    returnPlace: "この場所に戻る", history: "サンプル予約の履歴", switchStorage: "選択した場所を安全に開けませんでした。前の依頼は変わっていません。再試行してください。",
    storage: "このタブにサンプル依頼を保存できませんでした。新しい依頼は送信していません。", restore: "前回のサンプル予約を確認できます。", resultStorage: "結果を保存できませんでした。同じ依頼の結果をもう一度保存してください。", retryStorage: "結果を再保存",
  },
} as const
