import type { LocalizedText, Provenance, VenueFact } from "../../../features/ondo/contracts/domain"
import type { HeatReasonCode, MapNeighborhood, MapRegion, MapVenue } from "./models"

const at = "2026-08-18T15:10:00.000Z"

function provenance(fixtureId: string): Provenance {
  return {
    truth: "SIMULATED",
    fixtureId,
    sourceKind: "fixture",
    fetchedAt: at,
    expiresAt: "2026-08-20T11:10:00.000Z",
    isSimulation: true,
  }
}

function heatEvidence(fixtureId: string, minSampleMet: boolean, reasonCodes: HeatReasonCode[]) {
  return { minSampleMet, computedAt: at, reasonCodes, provenance: provenance(fixtureId) }
}

function text(en: string, ko: string): LocalizedText {
  return { en, ko }
}

function fact(id: string, en: string, ko: string, tone: VenueFact["tone"] = "positive", fixtureId = "FX-VENUE-SEOUL-001"): VenueFact {
  return {
    id,
    label: text(en, ko),
    value: text(en, ko),
    tone,
    provenance: provenance(fixtureId),
  }
}

export const MAP_REGIONS: MapRegion[] = [
  {
    id: "region-seoul",
    cityId: "seoul",
    name: text("Seoul", "서울"),
    latitude: 37.5665,
    longitude: 126.978,
    bounds: [[37.413, 126.734], [37.715, 127.269]],
    coverage: "complete",
    ondoScore: 87,
    heatLevel: "hot",
    signalCount: 142,
    confidence: "high",
    freshness: "today",
    ...heatEvidence("FX-MAP-SEOUL-RECENT", true, ["local_visits", "local_saves", "recent_contributions"]),
  },
  {
    id: "region-busan",
    cityId: "busan",
    name: text("Busan", "부산"),
    latitude: 35.1796,
    longitude: 129.0756,
    bounds: [[34.98, 128.75], [35.38, 129.32]],
    coverage: "seed",
    ondoScore: 84,
    heatLevel: "hot",
    signalCount: 12,
    confidence: "low",
    freshness: "today",
    nextExpansionLabel: text("Early coverage", "먼저 채워지는 지역"),
    ...heatEvidence("FX-MAP-BUSAN-SEED", true, ["local_visits", "editorial_signal"]),
  },
  {
    id: "region-jeju",
    name: text("Jeju", "제주"),
    latitude: 33.3617,
    longitude: 126.5292,
    bounds: [[33.11, 126.1], [33.61, 126.97]],
    coverage: "growing",
    ondoScore: null,
    heatLevel: "limited",
    signalCount: 0,
    confidence: "limited",
    freshness: "unknown",
    nextExpansionLabel: text("Growing signals", "신호를 모으는 중"),
    ...heatEvidence("FX-MAP-GROWING", false, ["insufficient_sample"]),
  },
  {
    id: "region-gangwon",
    name: text("Gangwon", "강원"),
    latitude: 37.5558,
    longitude: 128.2093,
    bounds: [[37.0, 127.4], [38.45, 129.35]],
    coverage: "growing",
    ondoScore: null,
    heatLevel: "limited",
    signalCount: 0,
    confidence: "limited",
    freshness: "unknown",
    nextExpansionLabel: text("Growing signals", "신호를 모으는 중"),
    ...heatEvidence("FX-MAP-GROWING", false, ["insufficient_sample"]),
  },
  {
    id: "region-jeonju",
    name: text("Jeonju", "전주"),
    latitude: 35.8242,
    longitude: 127.148,
    bounds: [[35.67, 126.96], [35.95, 127.3]],
    coverage: "growing",
    ondoScore: null,
    heatLevel: "limited",
    signalCount: 0,
    confidence: "limited",
    freshness: "unknown",
    nextExpansionLabel: text("Growing signals", "신호를 모으는 중"),
    ...heatEvidence("FX-MAP-GROWING", false, ["insufficient_sample"]),
  },
  {
    id: "region-gyeongju",
    name: text("Gyeongju", "경주"),
    latitude: 35.8562,
    longitude: 129.2247,
    bounds: [[35.64, 128.96], [36.08, 129.48]],
    coverage: "growing",
    ondoScore: null,
    heatLevel: "limited",
    signalCount: 0,
    confidence: "limited",
    freshness: "unknown",
    nextExpansionLabel: text("Growing signals", "신호를 모으는 중"),
    ...heatEvidence("FX-MAP-GROWING", false, ["insufficient_sample"]),
  },
]

export const MAP_NEIGHBORHOODS: MapNeighborhood[] = [
  { id: "seongsu", cityId: "seoul", name: text("Seongsu", "성수"), latitude: 37.5446, longitude: 127.0559, ondoScore: 92, heatLevel: "peak", signalCount: 38, confidence: "high", freshness: "today", ...heatEvidence("FX-MAP-SEOUL-RECENT", true, ["local_visits", "local_saves", "recent_contributions"]) },
  { id: "euljiro", cityId: "seoul", name: text("Euljiro", "을지로"), latitude: 37.566, longitude: 126.9917, ondoScore: 81, heatLevel: "hot", signalCount: 24, confidence: "high", freshness: "today", ...heatEvidence("FX-MAP-SEOUL-RECENT", true, ["local_visits", "recent_contributions"]) },
  { id: "mangwon", cityId: "seoul", name: text("Mangwon", "망원"), latitude: 37.5561, longitude: 126.9055, ondoScore: 58, heatLevel: "warming", signalCount: 11, confidence: "medium", freshness: "today", ...heatEvidence("FX-MAP-SEOUL-RECENT", true, ["local_visits", "local_saves"]) },
  { id: "jagalchi", cityId: "busan", name: text("Jagalchi", "자갈치"), latitude: 35.0967, longitude: 129.0306, ondoScore: 84, heatLevel: "hot", signalCount: 12, confidence: "low", freshness: "today", ...heatEvidence("FX-MAP-BUSAN-SEED", true, ["local_visits", "editorial_signal"]) },
]

export const MAP_VENUES: MapVenue[] = [
  {
    id: "seoul-seongsu-gukbap",
    cityId: "seoul",
    neighborhoodId: "seongsu",
    name: text("Seongsu Dwaeji Gukbap", "성수 돼지국밥"),
    category: text("Pork soup · local dinner", "돼지국밥 · 로컬 저녁"),
    description: text("A warming bowl locals save for the end of the workday.", "퇴근길 로컬 신호가 모이는 따뜻한 국밥 한 그릇이에요."),
    image: "/korean-kimchi-stew.png",
    latitude: 37.54463,
    longitude: 127.05591,
    address: text("Seongsu-dong 2-ga, Seongdong-gu, Seoul", "서울 성동구 성수동2가"),
    priceLabel: "₩10,000–15,000",
    distanceLabel: text("8 min walk", "도보 8분"),
    ondoScore: 92,
    heatLevel: "peak",
    signalCount: 14,
    confidence: "high",
    freshness: "today",
    updatedAt: "2026-08-18T15:58:00.000Z",
    reasons: [text("Local dinner saves and recent visits are rising.", "로컬 저녁 저장과 최근 방문 신호가 함께 늘고 있어요.")],
    facts: [
      fact("foreign_card", "Foreign-issued cards accepted", "해외 발급 카드 가능"),
      fact("korean_phone_required", "Korean phone number not required", "한국 전화번호 불필요"),
      fact("reservation_required", "Walk-in available", "현장 이용 가능"),
      fact("foreign_language", "English menu available", "영문 메뉴 있음"),
      fact("over19_required", "No age restriction", "연령 제한 없음", "neutral"),
    ],
    lateNight: false,
    alcohol: false,
    openingStatus: "open",
    coverage: "complete",
    sourceLabel: text("Recent local visits, saves, and contributions", "최근 로컬 방문·저장·기여 신호"),
    provenance: provenance("FX-VENUE-SEOUL-001"),
  },
  {
    id: "seoul-euljiro-nogari",
    cityId: "seoul",
    neighborhoodId: "euljiro",
    name: text("Euljiro Nogari Alley", "을지로 노가리 골목"),
    category: text("Dried pollack · beer", "노가리 · 맥주"),
    description: text("An outdoor evening classic with a clear 19+ condition for alcohol.", "야외 저녁 분위기를 즐기는 곳으로 주류 이용에는 19+ 조건이 있어요."),
    image: "/korean-fried-chicken.png",
    latitude: 37.56601,
    longitude: 126.99172,
    address: text("Euljiro 3-ga, Jung-gu, Seoul", "서울 중구 을지로3가"),
    priceLabel: "₩15,000–25,000",
    distanceLabel: text("3 min from Euljiro 3-ga", "을지로3가역 3분"),
    ondoScore: 84,
    heatLevel: "hot",
    signalCount: 18,
    confidence: "high",
    freshness: "today",
    updatedAt: "2026-08-18T15:44:00.000Z",
    reasons: [text("Evening contributions and local visits are rising.", "저녁 기여와 로컬 방문 신호가 늘고 있어요.")],
    facts: [
      fact("foreign_card", "Check card acceptance at the venue", "카드 이용 조건 현장 확인", "notice", "FX-MAP-SEOUL-RECENT"),
      fact("korean_phone_required", "Korean phone number not required", "한국 전화번호 불필요", "positive", "FX-MAP-SEOUL-RECENT"),
      fact("reservation_required", "Walk-in seating only", "현장 좌석만 가능", "notice", "FX-MAP-SEOUL-RECENT"),
      fact("foreign_language", "Language support information pending", "외국어 응대 정보 확인 중", "neutral", "FX-MAP-SEOUL-RECENT"),
      fact("over19_required", "19+ required for alcohol", "주류 이용 시 19+", "notice", "FX-MAP-SEOUL-RECENT"),
    ],
    lateNight: true,
    alcohol: true,
    openingStatus: "open",
    coverage: "complete",
    sourceLabel: text("Recent evening visits and contributions", "최근 저녁 방문·기여 신호"),
    provenance: provenance("FX-MAP-SEOUL-RECENT"),
  },
  {
    id: "seoul-mangwon-kalguksu",
    cityId: "seoul",
    neighborhoodId: "mangwon",
    name: text("Mangwon Market Kalguksu", "망원시장 칼국수"),
    category: text("Noodles · market meal", "칼국수 · 시장 한 끼"),
    description: text("A calmer market meal away from the busiest dinner zones.", "붐비는 저녁 지역에서 조금 벗어난 여유로운 시장 한 끼예요."),
    image: "/korean-bibimbap.png",
    latitude: 37.55612,
    longitude: 126.90552,
    address: text("Mangwon-dong, Mapo-gu, Seoul", "서울 마포구 망원동"),
    priceLabel: "₩7,000–10,000",
    distanceLabel: text("6 min walk", "도보 6분"),
    ondoScore: 58,
    heatLevel: "warming",
    signalCount: 7,
    confidence: "medium",
    freshness: "today",
    updatedAt: "2026-08-18T15:31:00.000Z",
    reasons: [text("A steady local lunch signal with a calmer pace.", "차분한 흐름 속에서 로컬 점심 신호가 꾸준해요.")],
    facts: [
      fact("foreign_card", "Cash or Korean card preferred", "현금·국내카드 권장", "notice", "FX-MAP-SEOUL-RECENT"),
      fact("korean_phone_required", "Korean phone number not required", "한국 전화번호 불필요", "positive", "FX-MAP-SEOUL-RECENT"),
      fact("reservation_required", "No reservation required", "예약 불필요", "positive", "FX-MAP-SEOUL-RECENT"),
      fact("foreign_language", "Photo menu available", "사진 메뉴 있음", "positive", "FX-MAP-SEOUL-RECENT"),
      fact("over19_required", "No age restriction", "연령 제한 없음", "neutral", "FX-MAP-SEOUL-RECENT"),
    ],
    lateNight: false,
    alcohol: false,
    openingStatus: "open",
    coverage: "complete",
    sourceLabel: text("Recent local lunch visits and saves", "최근 로컬 점심 방문·저장 신호"),
    provenance: provenance("FX-MAP-SEOUL-RECENT"),
  },
  {
    id: "busan-jagalchi-grill",
    cityId: "busan",
    neighborhoodId: "jagalchi",
    name: text("Jagalchi Charcoal Mackerel", "자갈치 숯불 고등어"),
    category: text("Grilled fish · Busan dinner", "생선구이 · 부산 저녁"),
    description: text("Early Busan coverage built from a smaller set of local dinner signals.", "적은 표본으로 먼저 시작한 부산 로컬 저녁 신호예요."),
    image: "/editorial-neighborhood-meal.jpg",
    latitude: 35.09672,
    longitude: 129.03061,
    address: text("Jagalchi-ro, Jung-gu, Busan", "부산 중구 자갈치로"),
    priceLabel: "₩15,000–25,000",
    distanceLabel: text("5 min from Jagalchi Market", "자갈치시장 도보 5분"),
    ondoScore: 84,
    heatLevel: "hot",
    signalCount: 12,
    confidence: "low",
    freshness: "today",
    updatedAt: "2026-08-18T15:42:00.000Z",
    reasons: [text("A small but recent set of grilled-fish dinner signals.", "작지만 최근 확인된 생선구이 저녁 신호가 있어요.")],
    facts: [
      fact("foreign_card", "Foreign-issued cards accepted", "해외 발급 카드 가능", "positive", "FX-MAP-BUSAN-SEED"),
      fact("korean_phone_required", "Korean phone number not required", "한국 전화번호 불필요", "positive", "FX-MAP-BUSAN-SEED"),
      fact("reservation_required", "Check same-day seating", "당일 좌석 확인 필요", "notice", "FX-MAP-BUSAN-SEED"),
      fact("foreign_language", "English picture menu", "영문 사진 메뉴", "positive", "FX-MAP-BUSAN-SEED"),
      fact("over19_required", "No age restriction", "연령 제한 없음", "neutral", "FX-MAP-BUSAN-SEED"),
    ],
    lateNight: false,
    alcohol: false,
    openingStatus: "open",
    coverage: "seed",
    sourceLabel: text("Busan early editorial coverage and recent local visits", "부산 초기 편집·최근 로컬 방문 신호"),
    provenance: provenance("FX-MAP-BUSAN-SEED"),
  },
]

export const MAP_VENUE_BY_ID = new Map(MAP_VENUES.map((venue) => [venue.id, venue]))

export function isStableVenueId(value: string): value is MapVenue["id"] {
  return MAP_VENUE_BY_ID.has(value)
}
