import { expect, test } from "@playwright/test"

test("TX16 order shortfall survives stablecoin funding; credit clears stale shortage without buying automatically", async ({ page, context }, info) => {
  test.setTimeout(120_000)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await context.route("**/*", async route => {
    const request = route.request(), url = new URL(request.url())
    if (!["GET", "HEAD", "OPTIONS"].includes(request.method()) || /sumsub|omni.?one|opendid|fullnode|sui\.io|walletconnect|stripe/i.test(url.hostname)) {
      errors.push(`Forbidden request: ${request.method()} ${url.origin}`)
      return route.abort("blockedbyclient")
    }
    return route.continue()
  })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/", { waitUntil: "domcontentloaded" })
  await expect(page.getByTestId("ondo-b-root")).toHaveAttribute("data-hydrated", "true")
  await page.getByTestId("nav-id").click()
  await page.getByTestId("wallet-link-open").click()
  const wallet = page.getByTestId("wallet-connect-sheet")
  await wallet.getByRole("button", { name: "Set up travel wallet", exact: true }).click()
  await expect(wallet).toHaveCount(0)
  await expect(page.getByTestId("wallet-balance")).toContainText("60,000")
  await page.getByTestId("wallet-balance-places").click()
  await page.getByTestId("ondo-b-view-toggle").click()
  await page.getByRole("button", { name: "Zest · Korean-ingredient cocktails", exact: true }).click()
  await page.getByTestId("place-offer-open").click()
  await expect(page.getByRole("heading", { name: "Review payment", exact: true })).toBeVisible()
  // Two ordinary UI payments make the third order insufficient. No seeded
  // account, balance, credential, receipt, or test-only operation is injected.
  for (let purchase = 0; purchase < 2; purchase++) {
    await page.getByTestId("payment-minimum-consent").getByRole("checkbox").check()
    await page.getByTestId("payment-confirm").click()
    if (purchase === 0) {
      await expect(page.getByTestId("ondo-b-action-gate")).toHaveAttribute("data-active-gate", "account")
      await page.getByTestId("action-gate-confirm").click()
      await expect(page.getByTestId("ondo-b-action-gate")).toHaveAttribute("data-active-gate", "payment_kyc")
      await page.getByTestId("action-gate-confirm").click()
    }
    await expect(page.getByTestId("payment-receipt")).toBeVisible()
    await page.getByTestId("payment-new-order").click()
    await expect(page.getByTestId("payment-receipt")).toHaveCount(0)
  }
  await expect(page.getByTestId("commerce-balance-shortage")).toContainText("24,000")
  await page.getByTestId("commerce-shortage-fund").click()
  const funding = page.getByTestId("funding-source-sheet")
  const contextLine = funding.getByTestId("funding-return-context")
  await expect(contextLine).toContainText("Zest")
  await expect(contextLine).toContainText("Shortfall before top-up: ₩24,000")
  await expect(contextLine).not.toContainText("confirm again")
  await funding.getByRole("radio", { name: /Stablecoins/ }).check()
  await funding.getByTestId("funding-method-save").click()
  await expect(funding.getByTestId("stablecoin-signer-zklogin")).toHaveText("Connect with a social account")
  await expect(funding.getByTestId("funding-amount-30000")).toHaveAttribute("aria-pressed", "true")
  await funding.getByTestId("stablecoin-technical-details").locator(":scope > summary").click()
  await expect(funding.getByTestId("stablecoin-technical-details")).toContainText("Sui zkLogin")
  await funding.getByTestId("stablecoin-technical-details").locator(":scope > summary").click()
  await page.screenshot({ path: info.outputPath("01-order-shortfall-and-connection-label.png"), fullPage: true })
  await funding.getByTestId("stablecoin-connect").click()
  await expect(funding.getByTestId("stablecoin-connection-preview")).toContainText("Connect sample wallet only")
  await funding.getByTestId("stablecoin-connection-approve").click()
  await funding.getByTestId("funding-quote-continue").click()
  await expect(funding).toContainText("20.25")
  await expect(funding).toContainText("Sui Testnet")
  await expect(funding).toContainText("0.25")
  await funding.getByTestId("funding-consent").check()
  await funding.getByTestId("funding-authorize").click()
  await expect(funding).toContainText("Balance arrival")
  await funding.getByTestId("stablecoin-check-source").click()
  await funding.getByTestId("stablecoin-check-destination").click()
  await expect(funding.getByTestId("funding-sample-use")).toBeVisible()
  await expect(funding.getByTestId("funding-receipt-balance")).toContainText("34,000")
  await expect(contextLine).not.toContainText("24,000")
  await expect(contextLine).toContainText("Adding funds is separate from paying the place.")
  await page.screenshot({ path: info.outputPath("02-credit-complete-no-stale-shortage.png"), fullPage: true })
  await funding.getByTestId("funding-sample-use").click()
  await expect(funding).toHaveCount(0)
  await expect(page.getByTestId("payment-receipt")).toHaveCount(0)
  await expect(page.getByTestId("payment-minimum-consent").getByRole("checkbox")).not.toBeChecked()
  await expect(page.getByTestId("payment-confirm")).toContainText("28,000")
  await page.getByTestId("payment-minimum-consent").getByRole("checkbox").check()
  await page.getByTestId("payment-confirm").click()
  await expect(page.getByTestId("payment-receipt")).toContainText("Zest")
  await page.getByTestId("payment-receipt-return").click()
  await expect(page.getByTestId("payment-receipt")).toHaveCount(0)
  await expect(page.getByTestId("researched-food-detail")).toHaveAttribute("data-research-id", "research-seoul-zest")
  expect(errors).toEqual([])
})
