import { expect, test, type Page } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"
import { expectBRuntimeClean, installBRuntimeGuard } from "../helpers/ondo-b-qa"

test.beforeEach(({ page }) => installBRuntimeGuard(page))
test.afterEach(async ({ page }, testInfo) => { await expectBRuntimeClean(page, testInfo) })

async function enterCounter(page: Page) {
  await page.goto("/", { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await page.locator('[data-testid="review-sample-indicator"]:visible').click()
  await page.getByTestId("integration-demo-open").click()
  await page.getByTestId("partner-sample-sign-in").click()
  await expect(page.getByTestId("partner-device-ready")).toBeDisabled()
  await page.getByTestId("partner-device-consent").check()
  await page.getByTestId("partner-device-ready").click()
}

for (const width of [320, 390, 1440]) test(`partner sample counter → permission → QR → minimal consent at ${width}px`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: width === 320 ? 740 : 900 })
  await enterCounter(page)
  await page.getByTestId("integration-verifier-create").click()
  const handoff = page.getByTestId("partner-request-handoff")
  const request = await handoff.getAttribute("data-request-ref")
  expect(request).toMatch(/^sample-request:/)
  await expect(page.getByTestId("partner-sample-qr")).toBeVisible()
  expect(await page.getByTestId("partner-sample-qr").locator("path").getAttribute("d")).toMatch(/^M/)
  await page.screenshot({ path: testInfo.outputPath(`partner-request-${width}.png`) })
  await page.getByTestId("integration-holder-open").click()
  await page.getByTestId("partner-camera-deny").click()
  await expect(handoff).toHaveAttribute("data-view", "denied")
  await expect(page.getByTestId("integration-verifier-result")).toHaveCount(0)
  await page.getByTestId("partner-return-counter").click()
  await expect(handoff).toHaveAttribute("data-request-ref", request!)
  await page.getByTestId("integration-holder-open").click()
  await page.getByTestId("partner-camera-allow").click()
  await expect(handoff).toHaveAttribute("data-view", "scan")
  await page.getByTestId("partner-qr-scan").click()
  await expect(page.getByTestId("integration-holder-request")).toHaveAttribute("data-phase", "consent")
  await page.screenshot({ path: testInfo.outputPath(`partner-consent-${width}.png`) })
  await page.getByTestId("integration-holder-approve").click()
  // Camera permission and consent cannot turn a guest into a verified person.
  await expect(page.getByTestId("integration-verifier-result")).toHaveAttribute("data-status", "needs_proof")
  await page.getByTestId("integration-tab-events").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(0)
  const dialog = page.getByRole("dialog", { name: "Partner tools", exact: true })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  const audit = await new AxeBuilder({ page }).include('[data-testid="integration-demo"]').analyze()
  expect(audit.violations.filter(v => v.impact === "serious" || v.impact === "critical")).toEqual([])
})

test("partner cancel, same-device request and expired request never synthesize eligibility", async ({ page }) => {
  await enterCounter(page)
  await page.getByTestId("integration-verifier-create").click()
  await page.getByTestId("partner-request-cancel").click()
  await expect(page.getByTestId("integration-verifier-result")).toContainText("Not shared")
  await page.getByTestId("integration-verifier-create").click()
  await page.getByTestId("partner-demo-deeplink").click()
  await page.getByTestId("integration-holder-deny").click()
  await expect(page.getByTestId("integration-verifier-result")).toContainText("Not shared")
  const scenario = page.getByTestId("integration-verifier-case")
  await scenario.locator("..").locator("summary").click()
  await scenario.selectOption("expired")
  await page.getByTestId("integration-verifier-create").click()
  await page.getByTestId("partner-demo-deeplink").click()
  await page.getByTestId("integration-holder-approve").click()
  await expect(page.getByTestId("integration-verifier-result")).toHaveAttribute("data-status", "expired")
  await expect(page.locator("input[type=file],video")).toHaveCount(0)
})
