import { expect, test, type Page } from "@playwright/test"
import { expectBRuntimeClean, installBRuntimeGuard } from "../helpers/ondo-b-qa"

test.beforeEach(({ page }) => installBRuntimeGuard(page))
test.afterEach(async ({ page }, testInfo) => { await expectBRuntimeClean(page, testInfo) })

async function start(page: Page) {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/", { waitUntil: "domcontentloaded" })
  // Public first entry is map-first; optional setup is no longer a gate.
  await expect(page.getByTestId("ondo-b-korea-atlas")).toBeVisible()
}

test("public Jeju cancellation unknown retains one booking through reload and permits a fresh booking only after resolution", async ({ page }, info) => {
  test.setTimeout(60_000)
  await start(page)
  await page.getByTestId("nav-tables").click()
  await page.getByTestId("tables-reservation-open").click()
  const sample = page.getByTestId("reservation-sample")
  await sample.getByRole("button", { name: "Jeju", exact: true }).click()
  await page.getByTestId("reservation-submit").click()
  await expect(sample).toHaveAttribute("data-phase", "confirmed")
  const originalId = await sample.getAttribute("data-operation-id")
  expect(originalId).toBeTruthy()
  const receipt = await sample.getByTestId("reservation-receipt").textContent()
  const response = page.getByTestId("reservation-cancel-outcome")
  await response.locator("xpath=ancestor::details").locator("summary").click()
  await response.selectOption("unknown")
  await page.getByTestId("reservation-cancel").click()
  await page.getByTestId("reservation-confirm-cancel").click()
  await expect(sample).toHaveAttribute("data-phase", "cancel_unknown")
  await expect(page.getByTestId("reservation-submit")).toHaveCount(0)
  await expect(page.getByTestId("reservation-cancel")).toHaveCount(0)
  await page.keyboard.press("Escape")
  await page.reload({ waitUntil: "domcontentloaded" })
  await page.getByTestId("nav-tables").click()
  await page.getByTestId("tables-reservation-open").click()
  await expect(sample).toHaveAttribute("data-phase", "cancel_unknown")
  await expect(sample).toHaveAttribute("data-operation-id", originalId!)
  await expect(sample.getByTestId("reservation-receipt")).toHaveText(receipt!)
  await expect(page.getByTestId("reservation-submit")).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("jeju-cancellation-unknown-restored.png") })
  await page.getByTestId("reservation-query").click()
  await expect(sample).toHaveAttribute("data-phase", "cancelled")
  await expect(sample).toHaveAttribute("data-operation-id", originalId!)
  await page.getByRole("button", { name: "Make another booking", exact: true }).click()
  await expect(sample).toHaveAttribute("data-phase", "draft")
  await expect(sample).toHaveAttribute("data-operation-id", "")
  await page.getByTestId("reservation-submit").click()
  await expect(sample).toHaveAttribute("data-phase", "confirmed")
  expect(await sample.getAttribute("data-operation-id")).not.toBe(originalId)
  await expect(sample.getByTestId("reservation-receipt")).toContainText("Jeju")
  await page.screenshot({ path: info.outputPath("jeju-fresh-booking-after-cancel.png") })
})

test("public Labs source-confirmed re-entry retains progress without destination receipt or consumer credit", async ({ page }, info) => {
  test.setTimeout(60_000)
  await start(page)
  await page.getByTestId("nav-id").click()
  const beforeBalance = await page.getByTestId("wallet-display-equivalent").textContent()
  // Read existing consumer state only; every operation below uses public UI.
  const beforeFunding = await page.evaluate(() => sessionStorage.getItem("ondo-b.funding-rail.v1"))
  await page.getByTestId("nav-my").click()
  await page.getByTestId("open-labs").click()
  await page.getByTestId("labs-acknowledge").click()
  const labs = page.getByTestId("labs-overlay")
  await labs.getByTestId("labs-connect-wallet").click()
  await labs.getByTestId("labs-bridge-quote").click()
  await labs.getByTestId("labs-bridge-confirm").click()
  await labs.getByTestId("labs-bridge-submit").click()
  await expect(labs).toHaveAttribute("data-bridge-phase", "source_submitted")
  await labs.getByTestId("labs-bridge-advance").click()
  await expect(labs).toHaveAttribute("data-bridge-phase", "source_confirmed")
  await expect(labs.getByTestId("labs-bridge-receipt")).toHaveCount(0)
  await labs.getByTestId("labs-back").click()
  await page.getByTestId("nav-id").click()
  await expect(page.getByTestId("wallet-display-equivalent")).toHaveText(beforeBalance!)
  await expect(page.getByTestId("wallet-activity-receipt")).toHaveCount(0)
  await page.getByTestId("nav-my").click()
  await page.getByTestId("open-labs").click()
  await expect(labs).toHaveAttribute("data-bridge-state", "BRG-PENDING")
  await expect(labs).toHaveAttribute("data-bridge-phase", "source_confirmed")
  await expect(labs.getByTestId("labs-bridge-submit")).toHaveCount(0)
  await expect(labs.getByTestId("labs-bridge-receipt")).toHaveCount(0)
  await labs.getByTestId("labs-bridge-advance").scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath("labs-source-confirmed-reentry.png") })
  await labs.getByTestId("labs-bridge-advance").click()
  await expect(labs).toHaveAttribute("data-bridge-phase", "relaying")
  await expect(labs.getByTestId("labs-bridge-receipt")).toHaveCount(0)
  await labs.getByTestId("labs-bridge-advance").click()
  await expect(labs).toHaveAttribute("data-bridge-state", "BRG-SIMULATED-SUCCESS")
  await expect(labs.getByTestId("labs-bridge-receipt")).toContainText("balances and transactions unchanged")
  expect(await page.evaluate(() => sessionStorage.getItem("ondo-b.funding-rail.v1"))).toBe(beforeFunding)
  await labs.getByTestId("labs-back").click()
  await page.getByTestId("nav-id").click()
  await expect(page.getByTestId("wallet-display-equivalent")).toHaveText(beforeBalance!)
  await expect(page.getByTestId("wallet-activity-receipt")).toHaveCount(0)
})
