import { expect, test, type Page } from "@playwright/test"
import { clickKPassService, preparePartnerDevice, runPartnerCheck } from "../helpers/ondo-demo-journey"
import { expectBRuntimeClean, installBRuntimeGuard } from "../helpers/ondo-b-qa"

test.use({ deviceScaleFactor: 1 })
test.beforeEach(({ page }) => installBRuntimeGuard(page))
test.afterEach(async ({ page }, testInfo) => { await expectBRuntimeClean(page, testInfo) })

async function openTools(page: Page) {
  await page.locator('[data-testid="review-sample-indicator"]:visible').click()
  await page.getByTestId("integration-demo-open").click()
  await expect(page.getByTestId("integration-demo")).toBeVisible()
  await preparePartnerDevice(page)
}
async function chooseCase(page: Page, value: string) {
  const select = page.getByTestId("integration-verifier-case")
  const details = select.locator("..")
  if ((await details.getAttribute("open")) === null) await details.locator("summary").click()
  await select.selectOption(value)
}
async function check(page: Page, consent = true) {
  await runPartnerCheck(page, consent)
}

test("public partner mock covers consent, binding failures and one-event retry with no injected credentials", async ({ page, baseURL }) => {
  test.setTimeout(100_000)
  await page.setViewportSize({ width: 390, height: 844 })
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto(`${baseURL}/`, { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await page.getByTestId("nav-id").click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-adult_visitor").click()
  await expect(page.getByTestId("kpass-scenario-adult_visitor")).toHaveCount(0)
  await openTools(page)
  for (const [scenario, status] of [["normal", "allowed"], ["wrong_audience", "denied"], ["replay", "denied"], ["expired", "expired"], ["revoked", "denied"]] as const) {
    await chooseCase(page, scenario)
    await check(page)
    await expect(page.getByTestId("integration-verifier-result")).toHaveAttribute("data-status", status)
    await page.screenshot({ path: test.info().outputPath(`verifier-${scenario}-390.png`) })
  }
  await chooseCase(page, "normal")
  await check(page, false)
  await expect(page.getByTestId("integration-verifier-result")).toContainText("Not shared")
  await page.getByTestId("integration-tab-events").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(1)
  await page.getByTestId("integration-voucher-issue").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(2)
  const outcome = page.getByTestId("integration-event-case")
  await outcome.locator("..").locator("summary").click()
  await outcome.selectOption("failure")
  await page.getByTestId("integration-event-KPassIssued").click()
  const issue = page.getByTestId("integration-event").filter({ hasText: "KPassIssued" })
  await expect(issue).toHaveAttribute("data-event-state", "failed")
  await page.getByTestId("integration-event-KPassIssued").click()
  await expect(issue).toHaveAttribute("data-event-state", "recorded")
  await expect(page.getByTestId("integration-event")).toHaveCount(2)
  await page.screenshot({ path: test.info().outputPath("events-390-light.png") })
  await page.getByRole("dialog", { name: "Partner tools", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  await expect(page.getByTestId("kpass-service-age")).toHaveAttribute("data-status", "allowed")
  await page.getByTestId("nav-settings").click()
  await page.getByTestId("settings-appearance-row").click()
  await page.getByTestId("settings-appearance-dark").click()
  await page.getByRole("dialog", { name: "Appearance", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  await page.getByTestId("nav-id").click()
  await openTools(page)
  await expect(page.getByTestId("integration-event")).toHaveCount(2)
  for (const width of [320, 390, 1280]) {
    await page.setViewportSize({ width, height: width === 320 ? 720 : 900 })
    const sheet = page.getByRole("dialog", { name: "Partner tools", exact: true })
    expect(await sheet.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
    for (const button of await sheet.locator("button:visible, summary:visible").all()) expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(43.99)
    await page.screenshot({ path: test.info().outputPath(`events-${width}-dark.png`) })
  }
  expect(errors).toEqual([])
})

test("guest partner check needs proof, creates no business events, and provider inspection is closed", async ({ page, baseURL }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto(`${baseURL}/`, { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await openTools(page)
  await check(page)
  await expect(page.getByTestId("integration-verifier-result")).toHaveAttribute("data-status", "needs_proof")
  await page.screenshot({ path: test.info().outputPath("guest-needs-proof-320.png") })
  await page.getByTestId("integration-tab-events").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(0)
  await expect(page.getByTestId("integration-voucher-issue")).toBeDisabled()
  await page.goto(`${baseURL}/?review=0`, { waitUntil: "domcontentloaded" })
  await expect(page.getByTestId("ondo-b-root")).toHaveAttribute("data-hydrated", "true")
  await expect(page.getByTestId("integration-demo")).toHaveCount(0)
  await expect(page.getByTestId("review-sample-indicator")).toHaveCount(0)
  expect(errors).toEqual([])
})

test("real sample checkout drives the six business events and a refund invalidates settlement", async ({ page, baseURL }) => {
  test.setTimeout(100_000)
  await page.setViewportSize({ width: 390, height: 844 })
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto(`${baseURL}/`, { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await page.getByTestId("nav-id").click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-adult_visitor").click()
  await expect(page.getByTestId("kpass-scenario-adult_visitor")).toHaveCount(0)
  await openTools(page)
  await page.getByTestId("integration-tab-events").click()
  await page.getByTestId("integration-voucher-issue").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(2)
  await page.getByRole("dialog", { name: "Partner tools", exact: true }).getByRole("button", { name: "Close", exact: true }).click()

  // The sample wallet and payment use the consumer-facing flow. No state,
  // sessionStorage, credential or payment record is inserted by the test.
  await clickKPassService(page, "visitor_benefit")
  await page.getByTestId("benefit-accept").click()
  await page.getByTestId("payment-confirm").click()
  const wallet = page.getByTestId("wallet-connect-sheet")
  await wallet.getByRole("button", { name: "Set up travel wallet", exact: true }).click()
  await expect(wallet).toHaveCount(0)
  await page.getByTestId("payment-minimum-consent").getByRole("checkbox").check()
  await page.getByTestId("payment-confirm").click()
  const gate = page.getByTestId("ondo-b-action-gate")
  for (const expected of ["account", "payment_kyc", "credential"]) {
    await expect(gate).toHaveAttribute("data-active-gate", expected)
    await gate.getByTestId("action-gate-confirm").click()
  }
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-completion-kind", "receipt")
  await page.getByTestId("payment-receipt-return").click()
  await expect(page.getByTestId("payment-receipt")).toHaveCount(0)
  const closePlace = page.getByRole("button", { name: "Close place", exact: true }).last()
  if (await closePlace.isVisible()) await closePlace.click()
  await page.getByTestId("nav-id").click()
  await openTools(page)
  await expect(page.getByTestId("integration-event")).toHaveCount(5)
  await expect(page.locator('[data-event-type="PaymentAuthorized"]')).toHaveCount(1)
  await expect(page.locator('[data-event-type="VoucherRedeemed"]')).toHaveCount(1)
  await page.getByTestId("integration-tab-settlements").click()
  const outcome = page.getByTestId("integration-settlement-case")
  await outcome.locator("..").locator("summary").click()
  await outcome.selectOption("failure")
  await page.getByTestId("integration-settlement-start").click()
  await expect(page.getByTestId("integration-settlement-state")).toHaveAttribute("data-status", "failed")
  await page.getByTestId("integration-settlement-start").click()
  await expect(page.getByTestId("integration-settlement-state")).toHaveAttribute("data-status", "settled")
  await page.screenshot({ path: test.info().outputPath("settlement-paid-390.png") })
  await page.getByTestId("integration-tab-events").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(6)
  await page.screenshot({ path: test.info().outputPath("six-business-events-390.png") })
  await page.getByRole("dialog", { name: "Partner tools", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  const activity = page.getByTestId("wallet-activity-receipt")
  await activity.locator(":scope > summary").click()
  await activity.getByTestId("wallet-activity-refund").click()
  await expect(activity.getByTestId("wallet-activity-refund")).toHaveCount(0)
  await openTools(page)
  await page.getByTestId("integration-tab-settlements").click()
  await expect(page.getByTestId("integration-settlement-state")).toHaveAttribute("data-status", "mismatched")
  await expect(page.getByTestId("integration-demo")).toContainText("₩0")
  await page.screenshot({ path: test.info().outputPath("settlement-refund-mismatch-390.png") })
  await page.getByTestId("integration-settlement-start").click()
  await expect(page.getByTestId("integration-settlement-state")).toHaveAttribute("data-status", "settled")
  await page.getByTestId("integration-tab-events").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(7)
  await expect(page.locator('[data-event-type="PaymentAuthorized"]')).toHaveCount(1)
  await expect(page.locator('[data-event-type="VoucherRedeemed"]')).toHaveCount(1)
  await expect(page.locator('[data-event-type="PartnerSettlementLogged"]')).toHaveCount(2)
  expect(errors).toEqual([])
})

test("public receipt retains its checked time but becomes stale after revocation and while open at expiry", async ({ page, baseURL }) => {
  test.setTimeout(70_000)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.clock.install()
  await page.goto(`${baseURL}/`, { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await page.getByTestId("nav-id").click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-adult_visitor").click()
  await expect(page.getByTestId("kpass-scenario-adult_visitor")).toHaveCount(0)
  await openTools(page)
  await check(page)
  const result = page.getByTestId("integration-verifier-result")
  await expect(result).toHaveAttribute("data-status", "allowed")
  const checkedAt = await page.getByTestId("integration-receipt-checked-at").getAttribute("datetime")
  await page.getByRole("dialog", { name: "Partner tools", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-revoked").click()
  await expect(page.getByTestId("kpass-scenario-revoked")).toHaveCount(0)
  await openTools(page)
  await expect(result).toHaveAttribute("data-status", "stale")
  await expect(result).toHaveAttribute("data-receipt-decision", "allowed")
  await expect(result).toHaveAttribute("data-receipt-current", "false")
  await expect(result.getByRole("heading")).toHaveText("Check again")
  await expect(page.getByTestId("integration-receipt-checked-at")).toHaveAttribute("datetime", checkedAt!)
  await page.screenshot({ path: test.info().outputPath("receipt-revoked-stale-390.png") })
  await page.getByRole("dialog", { name: "Partner tools", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-adult_visitor").click()
  await expect(page.getByTestId("kpass-scenario-adult_visitor")).toHaveCount(0)
  await openTools(page)
  await check(page)
  await expect(result).toHaveAttribute("data-status", "allowed")
  // Only the browser clock advances; credentials still come from the public
  // sample picker, and the UI's own deadline callback must invalidate it.
  await page.clock.fastForward(121_000)
  await expect(result).toHaveAttribute("data-status", "stale")
  await expect(result.getByRole("heading")).toHaveText("Check again")
  await page.screenshot({ path: test.info().outputPath("receipt-clock-stale-390.png") })
})

test("public age proof supplements one pass without duplicate issuance or voucher events", async ({ page, baseURL }) => {
  test.setTimeout(70_000)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`${baseURL}/`, { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await page.getByTestId("nav-id").click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-age_unknown").click()
  await expect(page.getByTestId("kpass-scenario-age_unknown")).toHaveCount(0)
  await openTools(page)
  await page.getByTestId("integration-tab-events").click()
  await page.getByTestId("integration-voucher-issue").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(2)
  await page.getByRole("dialog", { name: "Partner tools", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  await page.getByTestId("nav-tables").click()
  await page.getByTestId("table-open-table-seoul-night-bites").click()
  await page.getByTestId("table-join").click()
  const gate = page.getByTestId("ondo-b-action-gate")
  await expect(gate).toHaveAttribute("data-active-gate", "account")
  await gate.getByTestId("action-gate-confirm").click()
  await expect(page.getByTestId("kpass-policy-decision")).toHaveAttribute("data-reason", "age_proof_required")
  await page.getByTestId("kpass-request-age-proof").click()
  await expect(page.getByTestId("table-join-confirmation")).toBeVisible()
  await page.getByTestId("table-join-confirm").click()
  await expect(page.getByTestId("table-open-chat")).toBeVisible()
  await page.getByTestId("table-detail").getByRole("button", { name: "Close Table", exact: true }).click()
  await page.getByTestId("nav-id").click()
  await expect(page.getByTestId("kpass-service-age")).toHaveAttribute("data-status", "allowed")
  await openTools(page)
  await expect(page.getByTestId("integration-event")).toHaveCount(2)
  await page.getByTestId("integration-voucher-issue").click()
  await expect(page.getByTestId("integration-event")).toHaveCount(2)
  await expect(page.locator('[data-event-type="KPassIssued"]')).toHaveCount(1)
  await expect(page.locator('[data-event-type="VoucherIssued"]')).toHaveCount(1)
})

test("a real age supplement preserves the same payment owner so refund restores benefit and allowance", async ({ page, baseURL }) => {
  test.setTimeout(100_000)
  await page.setViewportSize({ width: 390, height: 844 })
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto(`${baseURL}/`, { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await page.getByTestId("nav-id").click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-age_unknown").click()
  await expect(page.getByTestId("kpass-scenario-age_unknown")).toHaveCount(0)
  await clickKPassService(page, "visitor_benefit")
  await page.getByTestId("benefit-accept").click()
  await page.getByTestId("payment-confirm").click()
  const wallet = page.getByTestId("wallet-connect-sheet")
  await wallet.getByRole("button", { name: "Set up travel wallet", exact: true }).click()
  await expect(wallet).toHaveCount(0)
  await page.getByTestId("payment-minimum-consent").getByRole("checkbox").check()
  await page.getByTestId("payment-confirm").click()
  const gate = page.getByTestId("ondo-b-action-gate")
  for (const expected of ["account", "payment_kyc", "credential"]) {
    await expect(gate).toHaveAttribute("data-active-gate", expected)
    await gate.getByTestId("action-gate-confirm").click()
  }
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-completion-kind", "receipt")
  await page.getByTestId("payment-receipt-return").click()
  await expect(page.getByTestId("payment-receipt")).toHaveCount(0)
  const closePlace = page.getByRole("button", { name: "Close place", exact: true }).last()
  if (await closePlace.isVisible()) await closePlace.click()
  await page.getByTestId("nav-id").click()
  await expect(page.getByTestId("kpass-service-visitor_benefit")).toHaveAttribute("data-status", "denied")
  await expect(page.getByTestId("kpass-service-card")).toContainText("₩81,000")
  const activity = page.getByTestId("wallet-activity-receipt")
  await activity.locator(":scope > summary").click()
  const originalReceipt = await activity.locator("code").first().textContent()

  // An actual service entry supplements the missing predicate. A sample
  // persona replacement would not test ownership of the original issuance.
  await page.getByTestId("nav-tables").click()
  await page.getByTestId("table-open-table-seoul-night-bites").click()
  await page.getByTestId("table-join").click()
  await expect(page.getByTestId("kpass-policy-decision")).toHaveAttribute("data-reason", "age_proof_required")
  await page.getByTestId("kpass-request-age-proof").click()
  await expect(page.getByTestId("table-join-confirmation")).toBeVisible()
  await page.getByTestId("table-join-confirm").click()
  await page.getByTestId("table-detail").getByRole("button", { name: "Close Table", exact: true }).click()
  await page.getByTestId("nav-id").click()
  await expect(page.getByTestId("kpass-service-age")).toHaveAttribute("data-status", "allowed")
  await expect(page.getByTestId("kpass-service-visitor_benefit")).toHaveAttribute("data-status", "denied")
  if ((await activity.getAttribute("open")) === null) await activity.locator(":scope > summary").click()
  await expect(activity.locator("code").first()).toHaveText(originalReceipt!)
  await activity.getByTestId("wallet-activity-refund").click()
  await expect(activity.getByTestId("wallet-activity-refund")).toHaveCount(0)
  await expect(activity.locator("code").first()).toHaveText(originalReceipt!)
  await expect(page.getByTestId("kpass-service-visitor_benefit")).toHaveAttribute("data-status", "allowed")
  await expect(page.getByTestId("kpass-service-card")).toContainText("₩100,000")
  await expect(page.getByTestId("kpass-service-age")).toHaveAttribute("data-status", "allowed")
  await expect(page.getByTestId("wallet-display-equivalent")).toHaveText("₩60,000")
  await page.getByTestId("kpass-service-card").scrollIntoViewIfNeeded()
  await page.screenshot({ path: test.info().outputPath("refund-after-age-proof-390.png") })
  await openTools(page)
  await page.getByTestId("integration-tab-events").click()
  await expect(page.locator('[data-event-type="KPassIssued"]')).toHaveCount(1)
  await expect(page.locator('[data-event-type="PaymentAuthorized"]')).toHaveCount(1)
  await expect(page.locator('[data-event-type="VoucherRedeemed"]')).toHaveCount(1)
  expect(errors).toEqual([])
})
