import { expect, test, type Page } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"
import { expectBRuntimeClean, installBRuntimeGuard } from "../helpers/ondo-b-qa"

test.beforeEach(({ page }) => installBRuntimeGuard(page))
test.afterEach(async ({ page }, testInfo) => { await expectBRuntimeClean(page, testInfo) })

async function start(page: Page, width = 390, dark = false) {
  await page.setViewportSize({ width, height: width === 320 ? 740 : 844 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/", { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  if (dark) {
    await page.getByTestId("nav-settings").click()
    await page.getByTestId("settings-appearance-row").click()
    await page.getByTestId("settings-appearance-dark").click()
    await page.keyboard.press("Escape")
  }
}
async function openReservation(page: Page) {
  await page.getByTestId("nav-tables").click()
  await page.getByTestId("tables-reservation-open").click()
  await expect(page.getByTestId("reservation-sample")).toBeVisible()
}
async function changeResponse(page: Page, id: string, value: string) {
  const select = page.getByTestId(id)
  const details = select.locator("xpath=ancestor::details")
  if (await details.getAttribute("open") === null) await details.locator("summary").click()
  await select.selectOption(value)
}
for (const [width, city, dark] of [[320, "Seoul", false], [390, "Busan", true], [430, "Jeju", false]] as const) {
  test(`public reservation: ${city}, ${width}px, confirmation and explicit cancellation`, async ({ page }, testInfo) => {
    // Includes navigation, accessibility analysis, a declined cancellation and
    // a confirmed cancellation; keep each state assertion's deadline unchanged.
    test.setTimeout(60_000)
    await start(page, width, dark); await openReservation(page)
    const sample = page.getByTestId("reservation-sample")
    await sample.getByRole("button", { name: city, exact: true }).click()
    await page.getByTestId("reservation-submit").click()
    await expect(sample).toHaveAttribute("data-phase", "confirmed")
    await expect(sample.getByTestId("reservation-receipt")).toContainText(city)
    await expect(sample.getByTestId("reservation-receipt")).toContainText("SAMPLE-")
    expect(await sample.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
    const result = await new AxeBuilder({ page }).include('[data-testid="reservation-sample"]').analyze()
    expect(result.violations.filter(v => v.impact === "serious" || v.impact === "critical")).toEqual([])
    await page.screenshot({ path: testInfo.outputPath(`reservation-${city}-${width}.png`) })
    await page.getByTestId("reservation-cancel").click()
    await page.getByRole("button", { name: "Keep booking", exact: true }).click()
    await expect(sample).toHaveAttribute("data-phase", "confirmed")
    await page.getByTestId("reservation-cancel").click()
    await page.getByTestId("reservation-confirm-cancel").click()
    await expect(sample).toHaveAttribute("data-phase", "cancelled")
    await page.keyboard.press("Escape")
    await expect(page.getByTestId("tables-reservation-open")).toBeFocused()
    expect(await page.evaluate(() => (window as Window & { __ONDO_B_QA__?: unknown }).__ONDO_B_QA__)).toBeUndefined()
  })
}
test("public booking in Jeju keeps one unknown operation through close, reload, query, and cancellation retry", async ({ page }, testInfo) => {
  await start(page); await openReservation(page)
  const sample = page.getByTestId("reservation-sample")
  await sample.getByRole("button", { name: "Jeju", exact: true }).click()
  await changeResponse(page, "reservation-outcome", "unknown")
  await page.getByTestId("reservation-submit").click()
  await expect(sample).toHaveAttribute("data-phase", "unknown")
  const id = await sample.getAttribute("data-operation-id")
  await expect(page.getByTestId("reservation-submit")).toHaveCount(0)
  await page.keyboard.press("Escape")
  await page.reload({ waitUntil: "domcontentloaded" })
  await openReservation(page)
  await expect(sample).toHaveAttribute("data-phase", "unknown")
  await expect(sample).toHaveAttribute("data-operation-id", id!)
  await page.getByTestId("reservation-query").click()
  await expect(sample).toHaveAttribute("data-phase", "confirmed")
  await expect(sample.getByTestId("reservation-receipt")).toContainText("Jeju")
  await changeResponse(page, "reservation-cancel-outcome", "failure")
  await page.getByTestId("reservation-cancel").click()
  await page.getByTestId("reservation-confirm-cancel").click()
  await expect(sample).toHaveAttribute("data-phase", "cancel_failed")
  await page.getByRole("button", { name: "Retry cancellation", exact: true }).click()
  await expect(sample).toHaveAttribute("data-phase", "cancelled")
  await expect(sample).toHaveAttribute("data-operation-id", id!)
  await page.screenshot({ path: testInfo.outputPath("reservation-jeju-reentry-cancelled.png") })
})
test("public no-seats and failed request preserve draft with an explicit next action", async ({ page }) => {
  await start(page); await openReservation(page)
  await page.getByLabel("People", { exact: true }).selectOption("4")
  await changeResponse(page, "reservation-outcome", "full")
  await page.getByTestId("reservation-submit").click()
  await expect(page.getByTestId("reservation-sample")).toHaveAttribute("data-phase", "full")
  await expect(page.getByLabel("People", { exact: true })).toHaveValue("4")
  await changeResponse(page, "reservation-outcome", "failure")
  await page.getByTestId("reservation-submit").click()
  await expect(page.getByTestId("reservation-sample")).toHaveAttribute("data-phase", "failed")
  await page.getByTestId("reservation-submit").click()
  await expect(page.getByTestId("reservation-sample")).toHaveAttribute("data-phase", "confirmed")
})
test("public account services expose export, session revoke, deletion and same-request recovery", async ({ page }, testInfo) => {
  test.setTimeout(60_000)
  await start(page, 320, true)
  await page.getByTestId("nav-settings").click()
  await page.getByTestId("ondo-b-device-data-settings").click()
  await page.getByTestId("account-services-open").click()
  const panel = page.getByTestId("account-services-sample")
  await changeResponse(page, "account-services-outcome", "unknown")
  await page.getByTestId("account-services-submit").click()
  await expect(panel).toHaveAttribute("data-phase", "unknown")
  const id = await panel.getAttribute("data-operation-id")
  await page.getByTestId("account-services-submit").click()
  await expect(panel).toHaveAttribute("data-phase", "done")
  await expect(panel).toHaveAttribute("data-operation-id", id!)
  const download = page.waitForEvent("download")
  await page.getByRole("button", { name: "Download sample JSON", exact: true }).click()
  expect((await download).suggestedFilename()).toBe("ondo-sample-account.json")
  await page.getByRole("button", { name: "Another service", exact: true }).click()
  await page.getByTestId("account-services-revoke").click()
  await page.getByTestId("account-services-submit").click()
  await expect(panel).toHaveAttribute("data-phase", "done")
  await expect(panel).toContainText("Signed out")
  await page.getByRole("button", { name: "Another service", exact: true }).click()
  await page.getByTestId("account-services-delete").click()
  await changeResponse(page, "account-services-outcome", "failure")
  await page.getByTestId("account-services-submit").click()
  await expect(panel).toHaveAttribute("data-phase", "failed")
  await page.getByTestId("account-services-submit").click()
  await expect(panel).toHaveAttribute("data-phase", "done")
  await expect(panel).toContainText("No real account or credential was revoked")
  expect(await panel.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("account-service-delete-320-dark.png") })
  await page.keyboard.press("Escape")
  await expect(page.getByTestId("account-services-open")).toBeFocused()
})
test("provider mode has no executable reservation or account-operation samples", async ({ page }) => {
  await page.goto("/?review=0", { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  await page.getByTestId("nav-tables").click()
  await expect(page.getByTestId("tables-reservation-open")).toHaveCount(0)
  await page.getByTestId("nav-settings").click()
  await page.getByTestId("ondo-b-device-data-settings").click()
  await expect(page.getByTestId("account-services-open")).toHaveCount(0)
})

for (const viewport of [{ width: 320, height: 460 }, { width: 844, height: 390 }]) {
  test(`public task footers stay reachable in a short viewport ${viewport.width}x${viewport.height}`, async ({ page }, testInfo) => {
    test.setTimeout(60_000)
    await start(page, 390, true)
    await openReservation(page)
    await page.setViewportSize(viewport)
    const submit = page.getByTestId("reservation-submit")
    await expect(submit).toBeInViewport()
    await submit.click()
    await expect(page.getByTestId("reservation-sample")).toHaveAttribute("data-phase", "confirmed")
    const cancel = page.getByTestId("reservation-cancel")
    await expect(cancel).toBeInViewport()
    const summary = page.getByTestId("reservation-sample").locator("details > summary")
    await summary.scrollIntoViewIfNeeded()
    const summaryBox = await summary.boundingBox()
    const doneBox = await page.getByRole("button", { name: "Done", exact: true }).boundingBox()
    expect(summaryBox!.y + summaryBox!.height).toBeLessThanOrEqual(doneBox!.y + 1)
    await cancel.click()
    await expect(page.getByTestId("reservation-confirm-cancel")).toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath(`reservation-short-${viewport.width}.png`) })
    await page.getByTestId("reservation-confirm-cancel").click()
    await expect(page.getByTestId("reservation-sample")).toHaveAttribute("data-phase", "cancelled")
    await page.keyboard.press("Escape")
    await expect(page.getByTestId("tables-reservation-open")).toBeFocused()
    await page.getByTestId("nav-settings").click()
    await page.getByTestId("ondo-b-device-data-settings").click()
    await page.getByTestId("account-services-open").click()
    await page.getByTestId("account-services-delete").click()
    await expect(page.getByTestId("account-services-submit")).toBeInViewport()
    expect(await page.locator("html").evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`account-short-${viewport.width}.png`) })
  })
}
