import { expect, test, type Page } from "@playwright/test"
import { readFileSync } from "node:fs"
import { expectBRuntimeClean, installBRuntimeGuard } from "../helpers/ondo-b-qa"

test.beforeEach(({ page }) => installBRuntimeGuard(page))
test.afterEach(async ({ page }, testInfo) => { await expectBRuntimeClean(page, testInfo) })

async function checkout(page: Page, options: { manual?: boolean; sampleCase?: string; dark?: boolean } = {}) {
  await page.goto("/", { waitUntil: "domcontentloaded" })
  await page.getByTestId("onboarding-guest-skip").click()
  if (options.dark) {
    await page.getByTestId("nav-settings").click()
    await page.getByTestId("settings-appearance-row").click()
    await page.getByTestId("settings-appearance-dark").click()
    await page.getByRole("dialog", { name: "Appearance", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  }
  await page.getByTestId("nav-id").click()
  await page.getByTestId("kpass-sample-picker").click()
  await page.getByTestId("kpass-scenario-adult_visitor").click()
  const services = page.getByTestId("kpass-service-disclosure")
  if (await services.getAttribute("open") === null) await services.locator(":scope > summary").click()
  await page.getByTestId("kpass-service-visitor_benefit").click()
  await page.getByTestId("benefit-accept").click()
  if (options.manual || options.sampleCase) {
    await page.getByTestId("payment-operation-options").locator("summary").click()
    if (options.manual) await page.getByTestId("payment-manual-capture").check()
    if (options.sampleCase) await page.getByTestId("payment-operation-case").selectOption(options.sampleCase)
  }
  await page.getByTestId("payment-confirm").click()
  await page.getByTestId("wallet-connect-sheet").getByRole("button", { name: "Set up travel wallet", exact: true }).click()
  await page.getByTestId("payment-minimum-consent").getByRole("checkbox").check()
  await page.getByTestId("payment-confirm").click()
  for (const expected of ["account", "payment_kyc", "credential"]) {
    const gate = page.getByTestId("ondo-b-action-gate")
    await expect(gate).toHaveAttribute("data-active-gate", expected)
    await gate.getByTestId("action-gate-confirm").click()
  }
}
async function returnToId(page: Page) {
  const closePlace = page.getByRole("button", { name: "Close place", exact: true }).last()
  if (await closePlace.isVisible()) await closePlace.click()
  await page.getByTestId("nav-id").click()
}

test("public approval/capture retry and whole-won partial then full refund preserve allowance and benefit", async ({ page }, info) => {
  test.setTimeout(100_000)
  await page.setViewportSize({ width: 320, height: 740 })
  await checkout(page, { manual: true, sampleCase: "capture_failure", dark: true })
  const operation = page.getByTestId("payment-operation")
  await expect(operation).toHaveAttribute("data-phase", "authorized")
  await expect(page.getByTestId("payment-held-amount")).toContainText("19,000")
  await expect(page.getByTestId("payment-receipt")).toHaveCount(0)
  expect(await operation.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("authorization-320-dark.png") })
  await page.getByTestId("payment-operation-continue").click()
  await expect(operation).toHaveAttribute("data-phase", "capture_failed")
  await page.getByTestId("payment-operation-continue").click()
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-completion-kind", "receipt")
  const refunds = page.getByTestId("checkout-refund-panel")
  await refunds.locator(":scope > summary").click()
  await page.getByTestId("checkout-refund-amount").fill("9501")
  await page.getByTestId("checkout-refund-submit").click()
  await expect(page.getByTestId("checkout-refund-total")).toContainText("9,501")
  await expect(page.getByTestId("checkout-refund-remaining")).toContainText("9,499")
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-refunded", "false")
  await expect(page.getByTestId("payment-partial-refund")).toContainText("9,501")
  await page.getByTestId("checkout-refund-case").locator("..").locator("summary").click()
  await page.getByTestId("checkout-refund-case").selectOption("unknown")
  await page.getByTestId("checkout-refund-all").click()
  await page.getByTestId("checkout-refund-submit").click()
  await expect(page.getByTestId("checkout-refund-operation").last()).toHaveAttribute("data-phase", "unknown")
  await expect(page.getByTestId("checkout-refund-total")).toContainText("9,501")
  await expect(page.getByTestId("checkout-refund-submit")).toHaveCount(0)
  expect(await refunds.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("partial-refund-query-320-dark.png") })
  await page.getByTestId("checkout-refund-check").click()
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-refunded", "true")
  await expect(page.getByTestId("checkout-refund-total")).toContainText("19,000")
  await page.getByTestId("payment-receipt-return").click()
  await returnToId(page)
  await expect(page.getByTestId("kpass-service-visitor_benefit")).toHaveAttribute("data-status", "allowed")
  await expect(page.getByTestId("kpass-service-card")).toContainText("100,000")
})

test("unknown capture survives closing, queries the same operation, and failed refund retries once", async ({ page }, info) => {
  test.setTimeout(100_000)
  await checkout(page, { sampleCase: "capture_unknown" })
  await expect(page.getByTestId("payment-operation")).toHaveAttribute("data-phase", "unknown")
  await page.getByTestId("payment-operation-back").click()
  await expect(page.getByTestId("payment-operation")).toHaveCount(0)
  await returnToId(page)
  await page.getByTestId("wallet-payment-resume").click()
  await expect(page.getByTestId("payment-operation")).toHaveAttribute("data-phase", "unknown")
  await expect(page.getByTestId("payment-confirm")).toHaveCount(0)
  await page.getByTestId("payment-operation-continue").click()
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-completion-kind", "receipt")
  await page.getByTestId("checkout-refund-panel").locator(":scope > summary").click()
  await page.getByTestId("checkout-refund-case").locator("..").locator("summary").click()
  await page.getByTestId("checkout-refund-case").selectOption("failure")
  await page.getByTestId("checkout-refund-submit").click()
  const operation = page.getByTestId("checkout-refund-operation")
  await expect(operation).toHaveAttribute("data-phase", "failed")
  const id = await operation.getAttribute("data-operation-id")
  await expect(page.getByTestId("checkout-refund-total")).toContainText("₩0")
  await page.getByTestId("checkout-refund-retry").click()
  await expect(operation).toHaveAttribute("data-phase", "settled")
  await expect(operation).toHaveAttribute("data-operation-id", id!)
  await expect(operation).toHaveCount(1)
  await expect(page.getByTestId("checkout-refund-total")).toContainText("5,000")
  await page.screenshot({ path: info.outputPath("refund-retry-same-operation-390.png") })
})

test("unknown approval can resolve as declined and retry without losing the original checkout", async ({ page }) => {
  test.setTimeout(90_000)
  await checkout(page, { sampleCase: "authorization_unknown" })
  const operation = page.getByTestId("payment-operation")
  await expect(operation).toHaveAttribute("data-phase", "unknown")
  await expect(page.getByTestId("payment-held-amount")).toContainText("₩0")
  await page.getByTestId("payment-query-failure").locator("..").locator("summary").click()
  await page.getByTestId("payment-query-failure").click()
  await expect(operation).toHaveAttribute("data-phase", "declined")
  await page.getByTestId("payment-operation-continue").click()
  await expect(page.getByTestId("payment-minimum-consent").getByRole("checkbox")).toBeChecked()
  await page.getByTestId("payment-confirm").click()
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-completion-kind", "receipt")
})

test("G11 support resumes one failed/unknown request and exports only a safe sample summary", async ({ page }, info) => {
  test.setTimeout(100_000)
  await page.setViewportSize({ width: 320, height: 740 })
  await checkout(page, { manual: true })
  await expect(page.getByRole("dialog", { name: "Payment status", exact: true })).toBeVisible()
  await page.getByTestId("payment-operation-continue").click()
  await expect(page.getByTestId("payment-receipt")).toHaveAttribute("data-completion-kind", "receipt")
  await page.getByTestId("payment-receipt-return").click()
  await returnToId(page)
  const openTools = async () => {
    await page.locator('[data-testid="review-sample-indicator"]:visible').click()
    await page.getByTestId("integration-demo-open").click()
    await page.getByTestId("integration-tab-settlements").click()
    const panel = page.getByTestId("integration-support-panel")
    if ((await panel.getAttribute("open")) === null) await panel.locator(":scope > summary").click()
  }
  await openTools()
  const sample = page.getByTestId("integration-support-case")
  await sample.locator("..").locator("summary").click()
  await sample.selectOption("failure")
  await page.getByTestId("integration-support-reason").selectOption("payment")
  await page.getByTestId("integration-support-start").click()
  const request = page.getByTestId("integration-support-request")
  await expect(request).toHaveAttribute("data-phase", "review")
  await expect(request).toContainText("₩19,000")
  const ref = await request.getAttribute("data-operation-ref")
  await page.getByTestId("integration-support-submit").click()
  await expect(request).toHaveAttribute("data-phase", "failed")
  await sample.selectOption("unknown")
  await page.getByTestId("integration-support-submit").click()
  await expect(request).toHaveAttribute("data-phase", "unknown")
  await page.getByRole("dialog", { name: "Partner tools", exact: true }).getByRole("button", { name: "Close", exact: true }).click()
  await openTools()
  await expect(request).toHaveAttribute("data-phase", "unknown")
  await expect(request).toHaveAttribute("data-operation-ref", ref!)
  await expect(page.getByTestId("integration-support-submit")).toHaveCount(0)
  await page.getByTestId("integration-support-check").click()
  await expect(request).toHaveAttribute("data-phase", "submitted")
  await expect(request).toHaveAttribute("data-operation-ref", ref!)
  await expect(page.getByTestId("integration-support-ticket")).toContainText("sample-ticket:")
  const downloadPromise = page.waitForEvent("download")
  await page.getByTestId("integration-settlement-export").click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe("ondo-sample-settlement.json")
  const summary = JSON.parse(readFileSync((await download.path())!, "utf8"))
  expect(summary).toEqual({ schemaVersion: 1, currency: "KRW", paymentReceiptRef: "ONDO-LOCAL-20260825-001", paymentKrw: 19000, refundKrw: 0, merchantNetKrw: 19000, provenanceTruth: "SIMULATED", externalProviderConnected: false, externalEffect: "none" })
  expect(await request.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath("settlement-support-ticket-320.png") })
  await page.getByTestId("integration-tab-events").click()
  await expect(page.locator('[data-event-type="PaymentAuthorized"]')).toHaveCount(1)
  await expect(page.locator('[data-event-type="PartnerSettlementLogged"]')).toHaveCount(0)
})
